//! Moshi temporal/depth language model for pre-tokenized Mimi streams.
//!
//! Moshi is not a single-stream causal LM, so it deliberately does not
//! implement [`super::common::CausalLm`]. The input to one temporal step is a
//! text token plus one token from every delayed audio codebook. The temporal
//! output predicts text; the depth transformer then predicts generated audio
//! codebooks autoregressively within the same frame.

use std::{collections::HashMap, path::Path};

use safemlx::{
    builder::Builder,
    error::Exception,
    fast::scaled_dot_product_attention,
    macros::ModuleParameters,
    module::{Module, ModuleParametersExt, Param},
    nn,
    ops::{indexing::TryIndexOp, maximum, r#where, zeros_like},
    Array, Dtype, Stream,
};
use serde::Deserialize;
use serde_json::Value;

use crate::{
    cache::{ConcatKeyValueCache, KeyValueCache},
    error::Error,
    weights::{load_safetensors_strict, StrictLoadConfig, StrictLoadReport},
};

const RMS_NORM_EPS: f32 = 1e-8;

fn default_true() -> bool {
    true
}

fn default_context() -> i32 {
    3_000
}

fn default_max_period() -> f32 {
    10_000.0
}

/// Fields consumed from the Moshi MLX `config.json` format.
#[derive(Debug, Clone, Deserialize)]
pub struct ModelArgs {
    /// Optional family marker. Early official Moshi configs omit this field.
    #[serde(default)]
    pub model_type: Option<String>,
    /// Temporal transformer width.
    pub dim: i32,
    /// Text vocabulary size, excluding the input-only padding token.
    pub text_card: i32,
    /// Number of Mimi audio codebooks across both dialogue streams.
    pub n_q: i32,
    /// Number of codebooks generated by the depth transformer.
    pub dep_q: i32,
    /// Mimi codebook cardinality.
    pub card: i32,
    /// Temporal attention head count.
    pub num_heads: i32,
    /// Temporal transformer layer count.
    pub num_layers: i32,
    /// Whether temporal attention is causal.
    #[serde(default = "default_true")]
    pub causal: bool,
    /// Temporal attention context.
    #[serde(default = "default_context")]
    pub context: i32,
    /// Temporal RoPE base.
    #[serde(default = "default_max_period")]
    pub max_period: f32,
    /// Temporal positional embedding kind (`rope` for released Moshi models).
    pub positional_embedding: String,
    /// Depth transformer width.
    pub depformer_dim: i32,
    /// Depth feed-forward width. Defaults to four times `depformer_dim`.
    #[serde(default)]
    pub depformer_dim_feedforward: Option<i32>,
    /// Depth attention head count.
    pub depformer_num_heads: i32,
    /// Depth transformer layer count.
    pub depformer_num_layers: i32,
    /// Depth attention context.
    #[serde(default)]
    pub depformer_context: Option<i32>,
    /// Depth RoPE base.
    #[serde(default)]
    pub depformer_max_period: Option<f32>,
    /// Depth positional embedding kind (`none` for released Moshi models).
    pub depformer_pos_emb: String,
    /// Delay for text followed by every audio codebook.
    pub delays: Vec<i32>,
    /// Optional checkpoint filename relative to the model directory.
    #[serde(default)]
    pub moshi_name: Option<String>,
    /// Conditioner definitions. Token-only milestone 1 supports empty maps.
    #[serde(default)]
    pub conditioners: HashMap<String, Value>,
    /// Whether temporal layers include cross attention.
    #[serde(default)]
    pub cross_attention: bool,
    /// Whether text tokens multiplex a second stream.
    #[serde(default)]
    pub demux_second_stream: bool,
    /// Optional low-rank depth embeddings.
    #[serde(default)]
    pub depformer_low_rank_embeddings: Option<i32>,
    /// Optional extra output heads.
    #[serde(default)]
    pub extra_heads_num_heads: i32,
}

impl ModelArgs {
    /// Configuration used by the original released Moshika/Moshiko MLX checkpoints.
    pub fn v0_1() -> Self {
        Self {
            model_type: Some("moshi".to_string()),
            dim: 4_096,
            text_card: 32_000,
            n_q: 16,
            dep_q: 8,
            card: 2_048,
            num_heads: 32,
            num_layers: 32,
            causal: true,
            context: 3_000,
            max_period: 10_000.0,
            positional_embedding: "rope".to_string(),
            depformer_dim: 1_024,
            depformer_dim_feedforward: Some(4_096),
            depformer_num_heads: 16,
            depformer_num_layers: 6,
            depformer_context: Some(8),
            depformer_max_period: Some(10_000.0),
            depformer_pos_emb: "none".to_string(),
            delays: vec![0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
            moshi_name: Some("model.safetensors".to_string()),
            conditioners: HashMap::new(),
            cross_attention: false,
            demux_second_stream: false,
            depformer_low_rank_embeddings: None,
            extra_heads_num_heads: 0,
        }
    }

    /// Input-only text padding token used to begin generation.
    pub fn text_padding_token(&self) -> i32 {
        self.text_card
    }

    /// Audio padding token used by the delayed-stream schedule.
    pub fn audio_padding_token(&self) -> i32 {
        self.card
    }

    /// Audio delays, excluding the leading text delay.
    pub fn audio_delays(&self) -> &[i32] {
        &self.delays[1..]
    }

    fn validate(&self) -> Result<(), Error> {
        if self.dim <= 0
            || self.text_card <= 0
            || self.n_q <= 0
            || self.dep_q <= 0
            || self.dep_q > self.n_q
            || self.card <= 0
            || self.num_heads <= 0
            || self.num_layers <= 0
            || self.depformer_dim <= 0
            || self.depformer_num_heads <= 0
            || self.depformer_num_layers <= 0
        {
            return Err(Error::UnsupportedArchitecture(
                "Moshi dimensions, vocabulary sizes, and layer counts must be positive".into(),
            ));
        }
        if self.dim % self.num_heads != 0 || self.depformer_dim % self.depformer_num_heads != 0 {
            return Err(Error::UnsupportedArchitecture(
                "Moshi transformer dimensions must be divisible by their head counts".into(),
            ));
        }
        if self.delays.len() != self.n_q as usize + 1 {
            return Err(Error::UnsupportedArchitecture(format!(
                "Moshi delays must contain text plus n_q entries (expected {}, got {})",
                self.n_q + 1,
                self.delays.len()
            )));
        }
        if !self.causal {
            return Err(Error::UnsupportedArchitecture(
                "non-causal Moshi temporal attention is not supported".into(),
            ));
        }
        if self.positional_embedding != "rope" || self.depformer_pos_emb != "none" {
            return Err(Error::UnsupportedArchitecture(format!(
                "expected Moshi positional embeddings rope/none, got {}/{}",
                self.positional_embedding, self.depformer_pos_emb
            )));
        }
        if self.cross_attention || !self.conditioners.is_empty() {
            return Err(Error::UnsupportedArchitecture(
                "Moshi conditioners and cross attention are outside token-only milestone 1".into(),
            ));
        }
        if self.demux_second_stream || self.depformer_low_rank_embeddings.is_some() {
            return Err(Error::UnsupportedArchitecture(
                "demultiplexed text and low-rank depth embeddings are not yet supported".into(),
            ));
        }
        if self.extra_heads_num_heads != 0 {
            return Err(Error::UnsupportedArchitecture(
                "Moshi extra heads are not part of token-only inference".into(),
            ));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct ScaledEmbedding {
    #[param]
    weight: Param<Array>,
}

impl ScaledEmbedding {
    fn unloaded(vocab: i32, dim: i32, stream: &Stream) -> Result<Self, Exception> {
        Ok(Self {
            weight: Param::<Array>::unloaded(&[vocab, dim], Dtype::Float32, stream)?,
        })
    }

    fn forward(&mut self, tokens: &Array, stream: &Stream) -> Result<Array, Exception> {
        let zero_mask = tokens.eq(Array::from_int(-1), stream)?;
        let safe_tokens = maximum(tokens, Array::from_int(0), stream)?;
        let embedded = self.weight.try_index_device(&safe_tokens, stream)?;
        r#where(
            &zero_mask.expand_dims(-1, stream)?,
            zeros_like(&embedded, stream)?,
            embedded,
            stream,
        )
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiAttention {
    num_heads: i32,
    head_dim: i32,
    scale: f32,
    context: i32,
    #[param]
    in_proj: nn::Linear,
    #[param]
    out_proj: nn::Linear,
    #[param]
    rope: Option<nn::Rope>,
}

impl MoshiAttention {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        let head_dim = cfg.dim / cfg.num_heads;
        let rope = cfg
            .rope
            .then(|| {
                nn::RopeBuilder::new(head_dim)
                    .traditional(true)
                    .base(cfg.max_period)
                    .build()
            })
            .transpose()?;
        Ok(Self {
            num_heads: cfg.num_heads,
            head_dim,
            scale: (head_dim as f32).sqrt().recip(),
            context: cfg.context,
            in_proj: nn::Linear::unloaded(cfg.dim, 3 * cfg.dim, false, Dtype::Float32, stream)?,
            out_proj: nn::Linear::unloaded(cfg.dim, cfg.dim, false, Dtype::Float32, stream)?,
            rope,
        })
    }

    fn forward(
        &mut self,
        x: &Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<Array, Exception> {
        Ok(self.forward_traced(x, cache, stream)?.output)
    }

    fn forward_traced(
        &mut self,
        x: &Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<AttentionTrace, Exception> {
        let shape = x.shape();
        if shape.len() != 3 || shape[1] != 1 {
            return Err(Exception::custom(
                "Moshi token inference currently requires [batch, 1, dim] steps",
            ));
        }
        let (batch, seq, dim) = (shape[0], shape[1], shape[2]);
        let in_proj = self.in_proj.forward(x, stream)?;
        let qkv = in_proj.reshape(&[batch, seq, 3, self.num_heads, self.head_dim], stream)?;
        let mut q = qkv
            .try_index_device((.., .., 0, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let mut k = qkv
            .try_index_device((.., .., 1, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let v = qkv
            .try_index_device((.., .., 2, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let offset = cache.offset();
        if let Some(rope) = &mut self.rope {
            q = rope.forward((&q, offset), stream)?;
            k = rope.forward((&k, offset), stream)?;
        }
        let queries = q.clone();
        let keys = k.clone();
        let (mut k, mut v) = cache.update_and_fetch(k, v, stream)?;
        let retained = (self.context + 1).min(k.dim(-2));
        if retained < k.dim(-2) {
            let start = k.dim(-2) - retained;
            k = k.try_index_device((.., .., start.., ..), stream)?;
            v = v.try_index_device((.., .., start.., ..), stream)?;
        }
        let attended = scaled_dot_product_attention(&q, &k, &v, self.scale, None, None, stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?
            .reshape(&[batch, seq, dim], stream)?;
        let output = self.out_proj.forward(&attended, stream)?;
        Ok(AttentionTrace {
            in_proj,
            queries,
            keys,
            values: v,
            attended,
            output,
        })
    }
}

struct AttentionTrace {
    in_proj: Array,
    queries: Array,
    keys: Array,
    values: Array,
    attended: Array,
    output: Array,
}

#[derive(Debug, Clone, Copy)]
struct TransformerConfig {
    dim: i32,
    num_heads: i32,
    num_layers: i32,
    feed_forward: i32,
    context: i32,
    max_period: f32,
    rope: bool,
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiMlp {
    hidden: i32,
    #[param]
    linear_in: nn::Linear,
    #[param]
    linear_out: nn::Linear,
}

impl MoshiMlp {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        let hidden = if cfg.feed_forward == 4 * cfg.dim {
            11 * cfg.dim / 4
        } else {
            2 * cfg.feed_forward / 3
        };
        Ok(Self {
            hidden,
            linear_in: nn::Linear::unloaded(cfg.dim, 2 * hidden, false, Dtype::Float32, stream)?,
            linear_out: nn::Linear::unloaded(hidden, cfg.dim, false, Dtype::Float32, stream)?,
        })
    }

    fn forward(&mut self, x: &Array, stream: &Stream) -> Result<Array, Exception> {
        let shape = x.shape();
        let projected = self
            .linear_in
            .forward(x, stream)?
            .reshape(&[shape[0], shape[1], 2, self.hidden], stream)?;
        let gate = nn::silu(projected.try_index_device((.., .., 0, ..), stream)?, stream)?;
        let value = projected.try_index_device((.., .., 1, ..), stream)?;
        self.linear_out
            .forward(&gate.multiply(value, stream)?, stream)
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiTransformerLayer {
    #[param]
    norm1: nn::RmsNorm,
    #[param]
    norm2: nn::RmsNorm,
    #[param]
    self_attn: MoshiAttention,
    #[param]
    gating: MoshiMlp,
}

impl MoshiTransformerLayer {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        Ok(Self {
            norm1: nn::RmsNorm::unloaded(cfg.dim, RMS_NORM_EPS, Dtype::Float32, stream)?,
            norm2: nn::RmsNorm::unloaded(cfg.dim, RMS_NORM_EPS, Dtype::Float32, stream)?,
            self_attn: MoshiAttention::unloaded(cfg, stream)?,
            gating: MoshiMlp::unloaded(cfg, stream)?,
        })
    }

    fn forward(
        &mut self,
        x: Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<Array, Exception> {
        let n1 = self.norm1.forward(&x, stream)?;
        let attn = self.self_attn.forward(&n1, cache, stream)?;
        let x = x.add(attn, stream)?;
        let n2 = self.norm2.forward(&x, stream)?;
        let mlp = self.gating.forward(&n2, stream)?;
        x.add(mlp, stream)
    }

    fn forward_traced(
        &mut self,
        x: Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<TemporalLayerTrace, Exception> {
        let norm1 = self.norm1.forward(&x, stream)?;
        let attention_trace = self.self_attn.forward_traced(&norm1, cache, stream)?;
        let post_attention = x.add(&attention_trace.output, stream)?;
        let norm2 = self.norm2.forward(&post_attention, stream)?;
        let mlp = self.gating.forward(&norm2, stream)?;
        let output = post_attention.add(&mlp, stream)?;
        Ok(TemporalLayerTrace {
            norm1,
            attention_in_proj: attention_trace.in_proj,
            attention_queries: attention_trace.queries,
            attention_keys: attention_trace.keys,
            attention_values: attention_trace.values,
            attention_attended: attention_trace.attended,
            attention: attention_trace.output,
            post_attention,
            norm2,
            mlp,
            output,
        })
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiTransformer {
    #[param]
    layers: Vec<MoshiTransformerLayer>,
}

impl MoshiTransformer {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        let layers = (0..cfg.num_layers)
            .map(|_| MoshiTransformerLayer::unloaded(cfg, stream))
            .collect::<Result<_, _>>()?;
        Ok(Self { layers })
    }

    fn forward(
        &mut self,
        mut x: Array,
        cache: &mut [ConcatKeyValueCache],
        stream: &Stream,
    ) -> Result<Array, Exception> {
        if cache.len() != self.layers.len() {
            return Err(Exception::custom("invalid Moshi transformer cache length"));
        }
        for (layer, cache) in self.layers.iter_mut().zip(cache) {
            x = layer.forward(x, cache, stream)?;
        }
        Ok(x)
    }

    fn forward_traced(
        &mut self,
        mut x: Array,
        cache: &mut [ConcatKeyValueCache],
        stream: &Stream,
    ) -> Result<(Array, Vec<TemporalLayerTrace>), Exception> {
        if cache.len() != self.layers.len() {
            return Err(Exception::custom("invalid Moshi transformer cache length"));
        }
        let mut layer_traces = Vec::with_capacity(self.layers.len());
        for (layer, cache) in self.layers.iter_mut().zip(cache) {
            let trace = layer.forward_traced(x, cache, stream)?;
            x = trace.output.clone();
            layer_traces.push(trace);
        }
        Ok((x, layer_traces))
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct DepFormerSlice {
    #[param]
    emb: ScaledEmbedding,
    #[param]
    linear_in: nn::Linear,
    #[param]
    linear_out: nn::Linear,
    #[param]
    transformer: MoshiTransformer,
}

impl DepFormerSlice {
    fn unloaded(
        input_vocab: i32,
        main_dim: i32,
        cfg: TransformerConfig,
        audio_vocab: i32,
        stream: &Stream,
    ) -> Result<Self, Exception> {
        Ok(Self {
            emb: ScaledEmbedding::unloaded(input_vocab, cfg.dim, stream)?,
            linear_in: nn::Linear::unloaded(main_dim, cfg.dim, false, Dtype::Float32, stream)?,
            linear_out: nn::Linear::unloaded(
                cfg.dim,
                audio_vocab - 1,
                false,
                Dtype::Float32,
                stream,
            )?,
            transformer: MoshiTransformer::unloaded(cfg, stream)?,
        })
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct DepFormer {
    #[param]
    slices: Vec<DepFormerSlice>,
}

/// Stateful caches for temporal and within-frame depth inference.
#[derive(Debug, Clone)]
pub struct MoshiCache {
    temporal: Vec<ConcatKeyValueCache>,
    depth: Vec<ConcatKeyValueCache>,
}

impl MoshiCache {
    /// Clears both temporal history and the current depth frame.
    pub fn reset(&mut self) {
        self.temporal
            .iter_mut()
            .for_each(|cache| *cache = Default::default());
        self.depth
            .iter_mut()
            .for_each(|cache| *cache = Default::default());
    }

    fn reset_depth(&mut self) {
        self.depth
            .iter_mut()
            .for_each(|cache| *cache = Default::default());
    }
}

/// Logits and hidden state produced for one teacher-forced Moshi frame.
pub struct TokenStepOutput {
    /// Sum of text and audio embeddings entering the temporal transformer.
    pub temporal_input: Array,
    /// Intermediate states from each temporal transformer layer.
    pub temporal_layer_traces: Vec<TemporalLayerTrace>,
    /// Temporal text logits, shaped `[batch, 1, text_card]`.
    pub text_logits: Array,
    /// One audio-logit tensor per generated codebook.
    pub audio_logits: Vec<Array>,
    /// Normalized temporal hidden state consumed by the depth transformer.
    pub temporal_output: Array,
}

/// Greedy text and generated-audio tokens for one frame.
pub struct GreedyStepOutput {
    /// Predicted text token, shaped `[batch, 1]`.
    pub text_token: Array,
    /// Predicted generated codebook tokens, shaped `[batch, dep_q]`.
    pub audio_tokens: Array,
    /// Raw logits retained for parity inspection.
    pub logits: TokenStepOutput,
}

/// Intermediate states retained for temporal-layer parity diagnostics.
pub struct TemporalLayerTrace {
    /// First RMS normalization output.
    pub norm1: Array,
    /// Fused QKV projection before head reshaping.
    pub attention_in_proj: Array,
    /// Query heads after rotary position encoding.
    pub attention_queries: Array,
    /// Current key heads after rotary position encoding.
    pub attention_keys: Array,
    /// Cached values supplied to scaled dot-product attention.
    pub attention_values: Array,
    /// Attention result after merging heads and before output projection.
    pub attention_attended: Array,
    /// Self-attention projection before the residual add.
    pub attention: Array,
    /// Residual state after self attention.
    pub post_attention: Array,
    /// Second RMS normalization output.
    pub norm2: Array,
    /// Gated MLP projection before the residual add.
    pub mlp: Array,
    /// Final layer residual state.
    pub output: Array,
}

/// Moshi temporal/depth token language model.
#[derive(Debug, Clone, ModuleParameters)]
pub struct Model {
    /// Parsed model configuration.
    pub args: ModelArgs,
    #[param]
    transformer: MoshiTransformer,
    #[param]
    depformer: DepFormer,
    #[param]
    text_emb: ScaledEmbedding,
    #[param]
    out_norm: nn::RmsNorm,
    #[param]
    text_linear: nn::Linear,
    #[param]
    audio_embs: Vec<ScaledEmbedding>,
}

impl Model {
    /// Creates an unloaded Moshi model from an MLX-format config.
    pub fn new(args: ModelArgs, stream: &Stream) -> Result<Self, Error> {
        args.validate()?;
        let temporal_cfg = TransformerConfig {
            dim: args.dim,
            num_heads: args.num_heads,
            num_layers: args.num_layers,
            feed_forward: 4 * args.dim,
            context: args.context,
            max_period: args.max_period,
            rope: true,
        };
        let depth_cfg = TransformerConfig {
            dim: args.depformer_dim,
            num_heads: args.depformer_num_heads,
            num_layers: args.depformer_num_layers,
            feed_forward: args
                .depformer_dim_feedforward
                .unwrap_or(4 * args.depformer_dim),
            context: args.depformer_context.unwrap_or(args.dep_q),
            max_period: args.depformer_max_period.unwrap_or(8.0),
            rope: false,
        };
        let mut slices = Vec::with_capacity(args.dep_q as usize);
        for index in 0..args.dep_q {
            let input_vocab = if index == 0 {
                args.text_card + 1
            } else {
                args.card + 1
            };
            slices.push(DepFormerSlice::unloaded(
                input_vocab,
                args.dim,
                depth_cfg,
                args.card + 1,
                stream,
            )?);
        }
        let audio_embs = (0..args.n_q)
            .map(|_| ScaledEmbedding::unloaded(args.card + 1, args.dim, stream))
            .collect::<Result<_, _>>()?;
        Ok(Self {
            transformer: MoshiTransformer::unloaded(temporal_cfg, stream)?,
            depformer: DepFormer { slices },
            text_emb: ScaledEmbedding::unloaded(args.text_card + 1, args.dim, stream)?,
            out_norm: nn::RmsNorm::unloaded(args.dim, RMS_NORM_EPS, Dtype::Float32, stream)?,
            text_linear: nn::Linear::unloaded(
                args.dim,
                args.text_card,
                false,
                Dtype::Float32,
                stream,
            )?,
            audio_embs,
            args,
        })
    }

    /// Allocates empty temporal and depth caches.
    pub fn new_cache(&self) -> MoshiCache {
        MoshiCache {
            temporal: vec![ConcatKeyValueCache::new(); self.args.num_layers as usize],
            depth: vec![ConcatKeyValueCache::new(); self.args.depformer_num_layers as usize],
        }
    }

    fn temporal_step(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<TemporalStepOutput, Exception> {
        if text_token.shape().len() != 2 || text_token.dim(1) != 1 {
            return Err(Exception::custom(
                "Moshi text input must have shape [batch, 1]",
            ));
        }
        if audio_tokens.shape().len() != 2
            || audio_tokens.dim(0) != text_token.dim(0)
            || audio_tokens.dim(1) != self.args.n_q
        {
            return Err(Exception::custom(format!(
                "Moshi audio input must have shape [batch, {}]",
                self.args.n_q
            )));
        }
        let mut x = self.text_emb.forward(text_token, stream)?;
        for (index, emb) in self.audio_embs.iter_mut().enumerate() {
            let token = audio_tokens
                .try_index_device((.., index as i32), stream)?
                .expand_dims(1, stream)?;
            x = x.add(emb.forward(&token, stream)?, stream)?;
        }
        let temporal_input = x.clone();
        let (hidden, layer_traces) =
            self.transformer
                .forward_traced(x, &mut cache.temporal, stream)?;
        let hidden = self.out_norm.forward(&hidden, stream)?;
        let logits = self.text_linear.forward(&hidden, stream)?;
        Ok(TemporalStepOutput {
            input: temporal_input,
            layer_traces,
            output: hidden,
            logits,
        })
    }

    fn depth_teacher_forced(
        &mut self,
        temporal_output: &Array,
        depth_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<Vec<Array>, Exception> {
        if depth_tokens.shape().len() != 2
            || depth_tokens.dim(0) != temporal_output.dim(0)
            || depth_tokens.dim(1) != self.args.dep_q
        {
            return Err(Exception::custom(format!(
                "Moshi depth input must have shape [batch, {}] (text then prior audio tokens)",
                self.args.dep_q
            )));
        }
        cache.reset_depth();
        let mut logits = Vec::with_capacity(self.args.dep_q as usize);
        for (index, slice) in self.depformer.slices.iter_mut().enumerate() {
            let token = depth_tokens
                .try_index_device((.., index as i32), stream)?
                .expand_dims(1, stream)?;
            let x = slice
                .linear_in
                .forward(temporal_output, stream)?
                .add(slice.emb.forward(&token, stream)?, stream)?;
            let x = slice.transformer.forward(x, &mut cache.depth, stream)?;
            logits.push(slice.linear_out.forward(&x, stream)?);
        }
        Ok(logits)
    }

    /// Runs one frame using teacher-forced depth inputs.
    ///
    /// `text_token` is `[batch, 1]`, `audio_tokens` is `[batch, n_q]`, and
    /// `depth_tokens` is `[batch, dep_q]`: sampled text followed by the first
    /// `dep_q - 1` generated audio tokens. This layout mirrors `moshi_mlx`'s
    /// slice-by-slice depth loop.
    pub fn token_step(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        depth_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<TokenStepOutput, Exception> {
        let temporal = self.temporal_step(text_token, audio_tokens, cache, stream)?;
        let audio_logits =
            self.depth_teacher_forced(&temporal.output, depth_tokens, cache, stream)?;
        Ok(TokenStepOutput {
            temporal_input: temporal.input,
            temporal_layer_traces: temporal.layer_traces,
            text_logits: temporal.logits,
            audio_logits,
            temporal_output: temporal.output,
        })
    }

    /// Runs one frame with greedy text and audio-codebook sampling.
    pub fn greedy_step(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<GreedyStepOutput, Exception> {
        let temporal = self.temporal_step(text_token, audio_tokens, cache, stream)?;
        let text = safemlx::argmax_axis!(&temporal.logits, -1, stream = stream)?;
        cache.reset_depth();
        let mut previous = text.clone();
        let mut predicted = Vec::with_capacity(self.args.dep_q as usize);
        let mut audio_logits = Vec::with_capacity(self.args.dep_q as usize);
        for slice in &mut self.depformer.slices {
            let x = slice
                .linear_in
                .forward(&temporal.output, stream)?
                .add(slice.emb.forward(&previous, stream)?, stream)?;
            let x = slice.transformer.forward(x, &mut cache.depth, stream)?;
            let logits = slice.linear_out.forward(&x, stream)?;
            previous = safemlx::argmax_axis!(&logits, -1, stream = stream)?;
            predicted.push(previous.squeeze_axes(&[-1], stream)?);
            audio_logits.push(logits);
        }
        let audio_tokens = safemlx::ops::stack_axis(&predicted, 1, stream)?;
        Ok(GreedyStepOutput {
            text_token: text,
            audio_tokens,
            logits: TokenStepOutput {
                temporal_input: temporal.input,
                temporal_layer_traces: temporal.layer_traces,
                text_logits: temporal.logits,
                audio_logits,
                temporal_output: temporal.output,
            },
        })
    }
}

struct TemporalStepOutput {
    input: Array,
    layer_traces: Vec<TemporalLayerTrace>,
    output: Array,
    logits: Array,
}

/// Reads and validates a Moshi MLX `config.json`.
///
/// When the file is absent, this returns [`ModelArgs::v0_1`], matching the
/// behavior used by `moshi_mlx` for the original Moshika/Moshiko releases.
pub fn get_model_args(model_dir: impl AsRef<Path>) -> Result<ModelArgs, Error> {
    let config_path = model_dir.as_ref().join("config.json");
    let args: ModelArgs = if config_path.exists() {
        serde_json::from_reader(std::fs::File::open(config_path)?)?
    } else {
        ModelArgs::v0_1()
    };
    args.validate()?;
    Ok(args)
}

/// Loads a BF16/FP16 Moshi MLX checkpoint for token-only inference.
///
/// Quantized `model.q4.safetensors` and `model.q8.safetensors` checkpoints are
/// intentionally rejected until Moshi's module-specific quantization layout is
/// represented in `safemlx-lm`.
pub fn load_model(
    model_dir: impl AsRef<Path>,
    stream: &Stream,
    weights_stream: &Stream,
) -> Result<Model, Error> {
    let model_dir = model_dir.as_ref();
    let args = get_model_args(model_dir)?;
    let weights_name = args
        .moshi_name
        .clone()
        .unwrap_or_else(|| "model.safetensors".to_string());
    if weights_name.contains(".q4.") || weights_name.contains(".q8.") {
        return Err(Error::UnsupportedArchitecture(format!(
            "quantized Moshi checkpoint {weights_name} is not supported; use the MLX BF16 checkpoint"
        )));
    }
    let mut model = Model::new(args, stream)?;
    let config = StrictLoadConfig::default();
    let mut report = StrictLoadReport::default();
    load_safetensors_strict(
        &mut model,
        model_dir.join(&weights_name),
        weights_stream,
        &config,
        &mut report,
    )?;
    report.finish(&model, &config)?;
    model.copy_to_stream(stream)?;
    Ok(model)
}

#[cfg(test)]
mod tests {
    use super::{Model, ModelArgs};
    use safemlx::{module::ModuleParameters, Device, DeviceType, ExecutionContext};

    fn minimal_config() -> &'static str {
        r#"{
            "dim": 16, "text_card": 32, "n_q": 4, "dep_q": 2, "card": 8,
            "num_heads": 4, "num_layers": 2, "causal": true, "context": 16,
            "max_period": 10000, "positional_embedding": "rope",
            "depformer_dim": 8, "depformer_dim_feedforward": 32,
            "depformer_num_heads": 2, "depformer_num_layers": 2,
            "depformer_context": 2, "depformer_pos_emb": "none",
            "delays": [0, 0, 1, 0, 1]
        }"#
    }

    #[test]
    fn parses_moshi_mlx_config() {
        let args: ModelArgs = serde_json::from_str(minimal_config()).unwrap();
        args.validate().unwrap();
        assert_eq!(args.text_padding_token(), 32);
        assert_eq!(args.audio_padding_token(), 8);
        assert_eq!(args.audio_delays(), &[0, 1, 0, 1]);
    }

    #[test]
    fn rejects_wrong_delay_count() {
        let mut value: serde_json::Value = serde_json::from_str(minimal_config()).unwrap();
        value["delays"] = serde_json::json!([0, 1]);
        let args: ModelArgs = serde_json::from_value(value).unwrap();
        assert!(args.validate().unwrap_err().to_string().contains("delays"));
    }

    #[test]
    fn released_v0_1_config_is_valid() {
        let args = ModelArgs::v0_1();
        args.validate().unwrap();
        assert_eq!(args.delays.len(), 17);
        assert_eq!(args.depformer_dim_feedforward, Some(4096));
    }

    #[test]
    #[ignore = "requires an MLX runtime with a Metal device"]
    fn parameter_names_match_moshi_mlx() {
        let ctx = ExecutionContext::new(Device::new(DeviceType::Cpu, 0));
        let args: ModelArgs = serde_json::from_str(minimal_config()).unwrap();
        let model = Model::new(args, ctx.stream()).unwrap();
        let params = model.parameters().flatten();
        for key in [
            "text_emb.weight",
            "audio_embs.0.weight",
            "out_norm.weight",
            "text_linear.weight",
            "transformer.layers.0.self_attn.in_proj.weight",
            "transformer.layers.0.gating.linear_in.weight",
            "depformer.slices.0.linear_in.weight",
            "depformer.slices.0.transformer.layers.0.norm1.weight",
        ] {
            assert!(params.contains_key(key), "missing parameter key {key}");
        }
    }
}
