//! Moshi temporal/depth language model for pre-tokenized Mimi streams.
//!
//! Moshi is not a single-stream causal LM, so it deliberately does not
//! implement [`super::common::CausalLm`]. The input to one temporal step is a
//! text token plus one token from every delayed audio codebook. The temporal
//! output predicts text; the depth transformer then predicts generated audio
//! codebooks autoregressively within the same frame.

use std::{collections::HashMap, path::Path};

use safemlx::{
    builder::Builder,
    error::Exception,
    fast::scaled_dot_product_attention,
    macros::ModuleParameters,
    module::{Module, ModuleParameters, ModuleParametersExt, Param},
    nn,
    ops::{
        addmm, dequantize_with_mode, indexing::TryIndexOp, matmul, maximum,
        quantized_matmul_with_mode, quantized_packed_dimension, r#where, split, zeros_like,
    },
    random::RandomState,
    transforms::compile::{
        compile_binary_with_stream_and_captures, compile_unary_with_stream_and_captures,
        CompiledBinaryWithStreamAndCaptures, CompiledUnaryWithStreamAndCaptures,
    },
    Array, Dtype, Stream,
};
use serde::Deserialize;
use serde_json::Value;

use crate::{
    cache::{ConcatKeyValueCache, KeyValueCache},
    error::Error,
    quantization::WeightQuantization,
    realtime::{
        self, RealtimeSampling, RealtimeSpeechConfig, RealtimeSpeechModel, RealtimeStepInput,
    },
    sampler::{DefaultSampler, Sampler},
    weights::{
        for_each_safetensor_array, load_array_quantized_strict, load_array_strict,
        load_safetensors_dir_strict, load_safetensors_quantized_strict, load_safetensors_strict,
        StrictLoadConfig, StrictLoadReport,
    },
};

const RMS_NORM_EPS: f32 = 1e-8;

type MoshiMlpFn = fn(&Array, &[Array], &Stream) -> Result<Array, Exception>;
type MoshiLayerPreFn = fn(&Array, &[Array], &Stream) -> Result<Array, Exception>;
type MoshiLayerPostFn = fn((&Array, &Array), &[Array], &Stream) -> Result<Array, Exception>;

fn default_true() -> bool {
    true
}

fn default_context() -> i32 {
    3_000
}

fn default_max_period() -> f32 {
    10_000.0
}

/// Fields consumed from the Moshi MLX `config.json` format.
#[derive(Debug, Clone, Deserialize)]
pub struct ModelArgs {
    /// Optional family marker. Early official Moshi configs omit this field.
    #[serde(default)]
    pub model_type: Option<String>,
    /// Temporal transformer width.
    pub dim: i32,
    /// Text vocabulary size, excluding the input-only padding token.
    pub text_card: i32,
    /// Optional existing tokenizer token used for text padding.
    #[serde(default)]
    pub existing_text_padding_id: Option<i32>,
    /// Number of Mimi audio codebooks across both dialogue streams.
    pub n_q: i32,
    /// Number of codebooks generated by the depth transformer.
    pub dep_q: i32,
    /// Number of generated-side audio codebooks returned to the codec.
    ///
    /// Defaults to `dep_q`, matching Moshi. PersonaPlex samples/forces more
    /// depth codebooks than it decodes as agent audio, so it uses a smaller
    /// generated-side count.
    #[serde(default, alias = "generated_q", alias = "audio_output_codebooks")]
    pub generated_audio_codebooks: Option<i32>,
    /// Mimi codebook cardinality.
    pub card: i32,
    /// Temporal attention head count.
    pub num_heads: i32,
    /// Temporal transformer layer count.
    pub num_layers: i32,
    /// Temporal feed-forward width. Defaults to four times `dim`.
    #[serde(default)]
    pub dim_feedforward: Option<i32>,
    /// Whether temporal attention is causal.
    #[serde(default = "default_true")]
    pub causal: bool,
    /// Temporal attention context.
    #[serde(default = "default_context")]
    pub context: i32,
    /// Temporal RoPE base.
    #[serde(default = "default_max_period")]
    pub max_period: f32,
    /// Temporal positional embedding kind (`rope` for released Moshi models).
    pub positional_embedding: String,
    /// Depth transformer width.
    pub depformer_dim: i32,
    /// Depth feed-forward width. Defaults to four times `depformer_dim`.
    #[serde(default)]
    pub depformer_dim_feedforward: Option<i32>,
    /// Depth attention head count.
    pub depformer_num_heads: i32,
    /// Depth transformer layer count.
    pub depformer_num_layers: i32,
    /// Depth attention context.
    #[serde(default)]
    pub depformer_context: Option<i32>,
    /// Depth RoPE base.
    #[serde(default)]
    pub depformer_max_period: Option<f32>,
    /// Depth positional embedding kind (`none` for released Moshi models).
    pub depformer_pos_emb: String,
    /// Delay for text followed by every audio codebook.
    pub delays: Vec<i32>,
    /// Optional checkpoint filename relative to the model directory.
    #[serde(default)]
    pub moshi_name: Option<String>,
    /// Conditioner definitions. Token-only milestone 1 supports empty maps.
    #[serde(default)]
    pub conditioners: HashMap<String, Value>,
    /// Whether temporal layers include cross attention.
    #[serde(default)]
    pub cross_attention: bool,
    /// Whether text tokens multiplex a second stream.
    #[serde(default)]
    pub demux_second_stream: bool,
    /// Optional low-rank depth embeddings.
    #[serde(default)]
    pub depformer_low_rank_embeddings: Option<i32>,
    /// Optional extra output heads.
    #[serde(default)]
    pub extra_heads_num_heads: i32,
    /// Optional MLX affine checkpoint quantization settings.
    #[serde(default)]
    pub quantization: Option<WeightQuantization>,
}

impl ModelArgs {
    /// Configuration used by the original released Moshika/Moshiko MLX checkpoints.
    pub fn v0_1() -> Self {
        Self {
            model_type: Some("moshi".to_string()),
            dim: 4_096,
            text_card: 32_000,
            existing_text_padding_id: None,
            n_q: 16,
            dep_q: 8,
            generated_audio_codebooks: None,
            card: 2_048,
            num_heads: 32,
            num_layers: 32,
            dim_feedforward: None,
            causal: true,
            context: 3_000,
            max_period: 10_000.0,
            positional_embedding: "rope".to_string(),
            depformer_dim: 1_024,
            depformer_dim_feedforward: Some(4_096),
            depformer_num_heads: 16,
            depformer_num_layers: 6,
            depformer_context: Some(8),
            depformer_max_period: Some(10_000.0),
            depformer_pos_emb: "none".to_string(),
            delays: vec![0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1],
            moshi_name: Some("model.safetensors".to_string()),
            conditioners: HashMap::new(),
            cross_attention: false,
            demux_second_stream: false,
            depformer_low_rank_embeddings: None,
            extra_heads_num_heads: 0,
            quantization: None,
        }
    }

    /// Input-only text padding token used to begin generation.
    pub fn text_padding_token(&self) -> i32 {
        self.existing_text_padding_id.unwrap_or(self.text_card)
    }

    /// Audio padding token used by the delayed-stream schedule.
    pub fn audio_padding_token(&self) -> i32 {
        self.card
    }

    /// Audio delays, excluding the leading text delay.
    pub fn audio_delays(&self) -> &[i32] {
        &self.delays[1..]
    }

    /// Number of generated-side audio codebooks emitted for decoding.
    pub fn generated_audio_codebooks(&self) -> i32 {
        self.generated_audio_codebooks.unwrap_or(self.dep_q)
    }

    /// Number of input-side audio codebooks consumed per realtime step.
    pub fn input_audio_codebooks(&self) -> i32 {
        self.n_q - self.generated_audio_codebooks()
    }

    fn validate(&self) -> Result<(), Error> {
        if let Some(quantization) = self.quantization {
            quantization.validate()?;
        }
        if self.dim <= 0
            || self.text_card <= 0
            || self.n_q <= 0
            || self.dep_q <= 0
            || self.card <= 0
            || self.num_heads <= 0
            || self.num_layers <= 0
            || self.depformer_dim <= 0
            || self.depformer_num_heads <= 0
            || self.depformer_num_layers <= 0
        {
            return Err(Error::UnsupportedArchitecture(
                "Moshi dimensions, vocabulary sizes, and layer counts must be positive".into(),
            ));
        }
        let generated = self.generated_audio_codebooks();
        if generated <= 0 || generated > self.dep_q || generated > self.n_q || self.dep_q > self.n_q
        {
            return Err(Error::UnsupportedArchitecture(format!(
                "Moshi generated/depth codebook counts must satisfy 0 < generated <= dep_q <= n_q (got generated={generated}, dep_q={}, n_q={})",
                self.dep_q, self.n_q
            )));
        }
        if let Some(token) = self.existing_text_padding_id {
            if token < 0 || token > self.text_card {
                return Err(Error::UnsupportedArchitecture(format!(
                    "Moshi existing text padding id must be in 0..={}; got {token}",
                    self.text_card
                )));
            }
        }
        if self.dim % self.num_heads != 0 || self.depformer_dim % self.depformer_num_heads != 0 {
            return Err(Error::UnsupportedArchitecture(
                "Moshi transformer dimensions must be divisible by their head counts".into(),
            ));
        }
        if self.delays.len() != self.n_q as usize + 1 {
            return Err(Error::UnsupportedArchitecture(format!(
                "Moshi delays must contain text plus n_q entries (expected {}, got {})",
                self.n_q + 1,
                self.delays.len()
            )));
        }
        if self.delays.iter().any(|delay| *delay < 0) {
            return Err(Error::UnsupportedArchitecture(
                "Moshi delays must be non-negative".into(),
            ));
        }
        if !self.causal {
            return Err(Error::UnsupportedArchitecture(
                "non-causal Moshi temporal attention is not supported".into(),
            ));
        }
        if self.positional_embedding != "rope" || self.depformer_pos_emb != "none" {
            return Err(Error::UnsupportedArchitecture(format!(
                "expected Moshi positional embeddings rope/none, got {}/{}",
                self.positional_embedding, self.depformer_pos_emb
            )));
        }
        if self.cross_attention || !self.conditioners.is_empty() {
            return Err(Error::UnsupportedArchitecture(
                "Moshi conditioners and cross attention are outside token-only milestone 1".into(),
            ));
        }
        if self.demux_second_stream || self.depformer_low_rank_embeddings.is_some() {
            return Err(Error::UnsupportedArchitecture(
                "demultiplexed text and low-rank depth embeddings are not yet supported".into(),
            ));
        }
        if self.extra_heads_num_heads != 0 {
            return Err(Error::UnsupportedArchitecture(
                "Moshi extra heads are not part of token-only inference".into(),
            ));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct ScaledEmbedding {
    #[param]
    weight: Param<Array>,
    #[param]
    scales: Param<Option<Array>>,
    #[param]
    biases: Param<Option<Array>>,
    quantization: Option<WeightQuantization>,
}

impl ScaledEmbedding {
    fn unloaded(
        vocab: i32,
        dim: i32,
        quantization: Option<WeightQuantization>,
        stream: &Stream,
    ) -> Result<Self, Exception> {
        let packed_dim =
            quantization.map_or(dim, |config| quantized_packed_dimension(dim, config.bits()));
        Ok(Self {
            weight: Param::<Array>::unloaded(
                &[vocab, packed_dim],
                if quantization.is_some() {
                    Dtype::Uint32
                } else {
                    Dtype::Float32
                },
                stream,
            )?,
            scales: Param::new(
                quantization
                    .map(|config| {
                        Param::<Array>::unloaded(
                            &[vocab, dim / config.group_size()],
                            if config == WeightQuantization::MxFp4 {
                                Dtype::Uint8
                            } else {
                                Dtype::Float32
                            },
                            stream,
                        )
                        .map(|param| param.value)
                    })
                    .transpose()?,
            ),
            biases: Param::new(
                quantization
                    .filter(|config| config.has_biases())
                    .map(|config| {
                        Param::<Array>::unloaded(
                            &[vocab, dim / config.group_size()],
                            Dtype::Float32,
                            stream,
                        )
                        .map(|param| param.value)
                    })
                    .transpose()?,
            ),
            quantization,
        })
    }

    fn selected_rows(&self, tokens: &Array, stream: &Stream) -> Result<Array, Exception> {
        let weight = self.weight.try_index_device(tokens, stream)?;
        if let Some(config) = self.quantization {
            let scales = self
                .scales
                .value
                .as_ref()
                .expect("quantized embedding scales")
                .try_index_device(tokens, stream)?;
            let biases = self
                .biases
                .value
                .as_ref()
                .map(|biases| biases.try_index_device(tokens, stream))
                .transpose()?;
            dequantize_with_mode(
                &weight,
                &scales,
                biases.as_ref(),
                config.group_size(),
                config.bits(),
                config.mode(),
                stream,
            )
        } else {
            Ok(weight)
        }
    }

    fn forward(&mut self, tokens: &Array, stream: &Stream) -> Result<Array, Exception> {
        let zero_mask = tokens.eq(Array::from_int(-1), stream)?;
        let safe_tokens = maximum(tokens, Array::from_int(0), stream)?;
        let embedded = self.selected_rows(&safe_tokens, stream)?;
        r#where(
            &zero_mask.expand_dims(-1, stream)?,
            zeros_like(&embedded, stream)?,
            embedded,
            stream,
        )
    }

    fn forward_nonnegative(&mut self, tokens: &Array, stream: &Stream) -> Result<Array, Exception> {
        self.selected_rows(tokens, stream)
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiLinear {
    #[param]
    weight: Param<Array>,
    #[param]
    bias: Param<Option<Array>>,
    #[param]
    scales: Param<Option<Array>>,
    #[param]
    biases: Param<Option<Array>>,
    quantization: Option<WeightQuantization>,
    weight_t: Option<Array>,
}

impl MoshiLinear {
    fn unloaded(
        input_dims: i32,
        output_dims: i32,
        bias: bool,
        dtype: Dtype,
        quantization: Option<WeightQuantization>,
        stream: &Stream,
    ) -> Result<Self, Exception> {
        let packed_input_dims = quantization.map_or(input_dims, |config| {
            quantized_packed_dimension(input_dims, config.bits())
        });
        Ok(Self {
            weight: Param::<Array>::unloaded(
                &[output_dims, packed_input_dims],
                if quantization.is_some() {
                    Dtype::Uint32
                } else {
                    dtype
                },
                stream,
            )?,
            bias: if bias {
                Param::<Option<Array>>::unloaded_some(&[output_dims], dtype, stream)?
            } else {
                Param::new(None)
            },
            scales: Param::new(
                quantization
                    .map(|config| {
                        Param::<Array>::unloaded(
                            &[output_dims, input_dims / config.group_size()],
                            if config == WeightQuantization::MxFp4 {
                                Dtype::Uint8
                            } else {
                                Dtype::Float32
                            },
                            stream,
                        )
                        .map(|param| param.value)
                    })
                    .transpose()?,
            ),
            biases: Param::new(
                quantization
                    .filter(|config| config.has_biases())
                    .map(|config| {
                        Param::<Array>::unloaded(
                            &[output_dims, input_dims / config.group_size()],
                            Dtype::Float32,
                            stream,
                        )
                        .map(|param| param.value)
                    })
                    .transpose()?,
            ),
            quantization,
            weight_t: None,
        })
    }

    fn forward(&mut self, x: &Array, stream: &Stream) -> Result<Array, Exception> {
        if let Some(config) = self.quantization {
            let output = quantized_matmul_with_mode(
                x,
                &self.weight,
                self.scales.value.as_ref().expect("quantized linear scales"),
                self.biases.value.as_ref(),
                true,
                config.group_size(),
                config.bits(),
                config.mode(),
                stream,
            )?;
            return match &self.bias.value {
                Some(bias) => output.add(bias, stream),
                None => Ok(output),
            };
        }
        let weight_t = self.weight_t(stream)?.clone();
        match &self.bias.value {
            Some(bias) => addmm(bias, x, &weight_t, None, None, stream),
            None => matmul(x, &weight_t, stream),
        }
    }

    fn weight_t(&mut self, stream: &Stream) -> Result<&Array, Exception> {
        if self.quantization.is_some() {
            return Err(Exception::custom(
                "packed affine weights do not have a dense transpose",
            ));
        }
        if self.weight_t.is_none() {
            self.weight_t = Some(self.weight.value.transpose(stream)?);
        }
        Ok(self.weight_t.as_ref().expect("cached transpose is set"))
    }

    fn is_quantized(&self) -> bool {
        self.quantization.is_some()
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiAttention {
    num_heads: i32,
    head_dim: i32,
    scale: f32,
    context: i32,
    #[param]
    in_proj: MoshiLinear,
    #[param]
    out_proj: MoshiLinear,
    #[param]
    rope: Option<nn::Rope>,
}

impl MoshiAttention {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        let head_dim = cfg.dim / cfg.num_heads;
        let rope = cfg
            .rope
            .then(|| {
                nn::RopeBuilder::new(head_dim)
                    .traditional(true)
                    .base(cfg.max_period)
                    .build()
            })
            .transpose()?;
        Ok(Self {
            num_heads: cfg.num_heads,
            head_dim,
            scale: (head_dim as f32).sqrt().recip(),
            context: cfg.context,
            in_proj: MoshiLinear::unloaded(
                cfg.dim,
                3 * cfg.dim,
                false,
                Dtype::Float32,
                cfg.quantization,
                stream,
            )?,
            out_proj: MoshiLinear::unloaded(
                cfg.dim,
                cfg.dim,
                false,
                Dtype::Float32,
                cfg.quantization,
                stream,
            )?,
            rope,
        })
    }

    fn attend_projected(
        &mut self,
        qkv: Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<Array, Exception> {
        let shape = qkv.shape();
        if shape.len() != 3 || shape[1] != 1 {
            return Err(Exception::custom(
                "Moshi projected attention currently requires [batch, 1, 3 * dim] steps",
            ));
        }
        let (batch, seq, dim) = (shape[0], shape[1], shape[2] / 3);
        let qkv = qkv.reshape(&[batch, seq, 3, self.num_heads, self.head_dim], stream)?;
        let mut q = qkv
            .try_index_device((.., .., 0, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let mut k = qkv
            .try_index_device((.., .., 1, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let v = qkv
            .try_index_device((.., .., 2, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let offset = cache.offset();
        if let Some(rope) = &mut self.rope {
            q = rope.forward((&q, offset), stream)?;
            k = rope.forward((&k, offset), stream)?;
        }
        let (mut k, mut v) = cache.update_and_fetch(k, v, stream)?;
        let retained = (self.context + 1).min(k.dim(-2));
        if retained < k.dim(-2) {
            let start = k.dim(-2) - retained;
            k = k.try_index_device((.., .., start.., ..), stream)?;
            v = v.try_index_device((.., .., start.., ..), stream)?;
        }
        scaled_dot_product_attention(&q, &k, &v, self.scale, None, None, stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?
            .reshape(&[batch, seq, dim], stream)
    }

    fn forward(
        &mut self,
        x: &Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<Array, Exception> {
        let projected = self.in_proj.forward(x, stream)?;
        let attended = self.attend_projected(projected, cache, stream)?;
        self.out_proj.forward(&attended, stream)
    }

    fn forward_traced(
        &mut self,
        x: &Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<AttentionTrace, Exception> {
        let shape = x.shape();
        if shape.len() != 3 || shape[1] != 1 {
            return Err(Exception::custom(
                "Moshi token inference currently requires [batch, 1, dim] steps",
            ));
        }
        let (batch, seq, dim) = (shape[0], shape[1], shape[2]);
        let in_proj = self.in_proj.forward(x, stream)?;
        let qkv = in_proj.reshape(&[batch, seq, 3, self.num_heads, self.head_dim], stream)?;
        let mut q = qkv
            .try_index_device((.., .., 0, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let mut k = qkv
            .try_index_device((.., .., 1, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let v = qkv
            .try_index_device((.., .., 2, .., ..), stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?;
        let offset = cache.offset();
        if let Some(rope) = &mut self.rope {
            q = rope.forward((&q, offset), stream)?;
            k = rope.forward((&k, offset), stream)?;
        }
        let queries = q.clone();
        let keys = k.clone();
        let (mut k, mut v) = cache.update_and_fetch(k, v, stream)?;
        let retained = (self.context + 1).min(k.dim(-2));
        if retained < k.dim(-2) {
            let start = k.dim(-2) - retained;
            k = k.try_index_device((.., .., start.., ..), stream)?;
            v = v.try_index_device((.., .., start.., ..), stream)?;
        }
        let attended = scaled_dot_product_attention(&q, &k, &v, self.scale, None, None, stream)?
            .transpose_axes(&[0, 2, 1, 3], stream)?
            .reshape(&[batch, seq, dim], stream)?;
        let output = self.out_proj.forward(&attended, stream)?;
        Ok(AttentionTrace {
            in_proj,
            queries,
            keys,
            values: v,
            attended,
            output,
        })
    }
}

struct AttentionTrace {
    in_proj: Array,
    queries: Array,
    keys: Array,
    values: Array,
    attended: Array,
    output: Array,
}

#[derive(Debug, Clone, Copy)]
struct TransformerConfig {
    dim: i32,
    num_heads: i32,
    num_layers: i32,
    feed_forward: i32,
    context: i32,
    max_period: f32,
    rope: bool,
    quantization: Option<WeightQuantization>,
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiMlp {
    #[param]
    linear_in: MoshiLinear,
    #[param]
    linear_out: MoshiLinear,
    compiled: CompiledUnaryWithStreamAndCaptures<MoshiMlpFn>,
}

impl MoshiMlp {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        let hidden = if cfg.feed_forward == 4 * cfg.dim {
            11 * cfg.dim / 4
        } else {
            2 * cfg.feed_forward / 3
        };
        Ok(Self {
            linear_in: MoshiLinear::unloaded(
                cfg.dim,
                2 * hidden,
                false,
                Dtype::Float32,
                cfg.quantization,
                stream,
            )?,
            linear_out: MoshiLinear::unloaded(
                hidden,
                cfg.dim,
                false,
                Dtype::Float32,
                cfg.quantization,
                stream,
            )?,
            compiled: compile_unary_with_stream_and_captures(moshi_mlp as MoshiMlpFn, [], false),
        })
    }

    fn forward(&mut self, x: &Array, stream: &Stream) -> Result<Array, Exception> {
        if self.linear_in.is_quantized() {
            let projected = self.linear_in.forward(x, stream)?;
            let mut parts = split(projected, 2, -1, stream)?;
            let gate = nn::silu(parts.remove(0), stream)?;
            return self
                .linear_out
                .forward(&gate.multiply(parts.remove(0), stream)?, stream);
        }
        if self.compiled.captures().is_empty() {
            self.compiled.set_captures([
                self.linear_in.weight_t(stream)?.clone(),
                self.linear_out.weight_t(stream)?.clone(),
            ]);
        }
        self.compiled.call(x, stream)
    }
}

fn moshi_mlp(x: &Array, captures: &[Array], stream: &Stream) -> Result<Array, Exception> {
    let projected = matmul(x, &captures[0], stream)?;
    let mut parts = split(projected, 2, -1, stream)?;
    let gate = nn::silu(parts.remove(0), stream)?;
    matmul(
        &gate.multiply(parts.remove(0), stream)?,
        &captures[1],
        stream,
    )
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiTransformerLayer {
    #[param]
    norm1: nn::RmsNorm,
    #[param]
    norm2: nn::RmsNorm,
    #[param]
    self_attn: MoshiAttention,
    #[param]
    gating: MoshiMlp,
    compiled_pre: CompiledUnaryWithStreamAndCaptures<MoshiLayerPreFn>,
    compiled_post: CompiledBinaryWithStreamAndCaptures<MoshiLayerPostFn>,
}

impl MoshiTransformerLayer {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        Ok(Self {
            norm1: nn::RmsNorm::unloaded(cfg.dim, RMS_NORM_EPS, Dtype::Float32, stream)?,
            norm2: nn::RmsNorm::unloaded(cfg.dim, RMS_NORM_EPS, Dtype::Float32, stream)?,
            self_attn: MoshiAttention::unloaded(cfg, stream)?,
            gating: MoshiMlp::unloaded(cfg, stream)?,
            compiled_pre: compile_unary_with_stream_and_captures(
                moshi_layer_pre as MoshiLayerPreFn,
                [],
                false,
            ),
            compiled_post: compile_binary_with_stream_and_captures(
                moshi_layer_post as MoshiLayerPostFn,
                [],
                false,
            ),
        })
    }

    fn forward(
        &mut self,
        x: Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<Array, Exception> {
        if self.self_attn.in_proj.is_quantized() {
            let norm1 = self.norm1.forward(&x, stream)?;
            let attention = self.self_attn.forward(&norm1, cache, stream)?;
            let post_attention = x.add(attention, stream)?;
            let norm2 = self.norm2.forward(&post_attention, stream)?;
            let mlp = self.gating.forward(&norm2, stream)?;
            return post_attention.add(mlp, stream);
        }
        if self.compiled_pre.captures().is_empty() {
            let in_proj = self.self_attn.in_proj.weight_t(stream)?.clone();
            self.compiled_pre
                .set_captures([self.norm1.weight.value.clone(), in_proj]);
        }
        if self.compiled_post.captures().is_empty() {
            let out_proj = self.self_attn.out_proj.weight_t(stream)?.clone();
            let mlp_in = self.gating.linear_in.weight_t(stream)?.clone();
            let mlp_out = self.gating.linear_out.weight_t(stream)?.clone();
            self.compiled_post.set_captures([
                out_proj,
                self.norm2.weight.value.clone(),
                mlp_in,
                mlp_out,
            ]);
        }
        let qkv = self.compiled_pre.call(&x, stream)?;
        let attended = self.self_attn.attend_projected(qkv, cache, stream)?;
        self.compiled_post.call(&x, &attended, stream)
    }

    fn forward_traced(
        &mut self,
        x: Array,
        cache: &mut ConcatKeyValueCache,
        stream: &Stream,
    ) -> Result<TemporalLayerTrace, Exception> {
        let norm1 = self.norm1.forward(&x, stream)?;
        let attention_trace = self.self_attn.forward_traced(&norm1, cache, stream)?;
        let post_attention = x.add(&attention_trace.output, stream)?;
        let norm2 = self.norm2.forward(&post_attention, stream)?;
        let mlp = self.gating.forward(&norm2, stream)?;
        let output = post_attention.add(&mlp, stream)?;
        Ok(TemporalLayerTrace {
            norm1,
            attention_in_proj: attention_trace.in_proj,
            attention_queries: attention_trace.queries,
            attention_keys: attention_trace.keys,
            attention_values: attention_trace.values,
            attention_attended: attention_trace.attended,
            attention: attention_trace.output,
            post_attention,
            norm2,
            mlp,
            output,
        })
    }
}

fn moshi_layer_pre(x: &Array, captures: &[Array], stream: &Stream) -> Result<Array, Exception> {
    let normalized = safemlx::fast::rms_norm(x, &captures[0], RMS_NORM_EPS, stream)?;
    matmul(&normalized, &captures[1], stream)
}

fn moshi_layer_post(
    (residual, attended): (&Array, &Array),
    captures: &[Array],
    stream: &Stream,
) -> Result<Array, Exception> {
    let x = residual.add(matmul(attended, &captures[0], stream)?, stream)?;
    let normalized = safemlx::fast::rms_norm(&x, &captures[1], RMS_NORM_EPS, stream)?;
    let projected = matmul(&normalized, &captures[2], stream)?;
    let mut parts = split(projected, 2, -1, stream)?;
    let gate = nn::silu(parts.remove(0), stream)?;
    let mlp = matmul(
        &gate.multiply(parts.remove(0), stream)?,
        &captures[3],
        stream,
    )?;
    x.add(mlp, stream)
}

#[derive(Debug, Clone, ModuleParameters)]
struct MoshiTransformer {
    #[param]
    layers: Vec<MoshiTransformerLayer>,
}

impl MoshiTransformer {
    fn unloaded(cfg: TransformerConfig, stream: &Stream) -> Result<Self, Exception> {
        let layers = (0..cfg.num_layers)
            .map(|_| MoshiTransformerLayer::unloaded(cfg, stream))
            .collect::<Result<_, _>>()?;
        Ok(Self { layers })
    }

    fn forward(
        &mut self,
        mut x: Array,
        cache: &mut [ConcatKeyValueCache],
        stream: &Stream,
    ) -> Result<Array, Exception> {
        if cache.len() != self.layers.len() {
            return Err(Exception::custom("invalid Moshi transformer cache length"));
        }
        for (layer, cache) in self.layers.iter_mut().zip(cache) {
            x = layer.forward(x, cache, stream)?;
        }
        Ok(x)
    }

    fn forward_traced(
        &mut self,
        mut x: Array,
        cache: &mut [ConcatKeyValueCache],
        stream: &Stream,
    ) -> Result<(Array, Vec<TemporalLayerTrace>), Exception> {
        if cache.len() != self.layers.len() {
            return Err(Exception::custom("invalid Moshi transformer cache length"));
        }
        let mut layer_traces = Vec::with_capacity(self.layers.len());
        for (layer, cache) in self.layers.iter_mut().zip(cache) {
            let trace = layer.forward_traced(x, cache, stream)?;
            x = trace.output.clone();
            layer_traces.push(trace);
        }
        Ok((x, layer_traces))
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct DepFormerSlice {
    #[param]
    emb: ScaledEmbedding,
    #[param]
    linear_in: MoshiLinear,
    #[param]
    linear_out: MoshiLinear,
    #[param]
    transformer: MoshiTransformer,
}

impl DepFormerSlice {
    fn unloaded(
        input_vocab: i32,
        main_dim: i32,
        cfg: TransformerConfig,
        audio_vocab: i32,
        stream: &Stream,
    ) -> Result<Self, Exception> {
        Ok(Self {
            emb: ScaledEmbedding::unloaded(input_vocab, cfg.dim, cfg.quantization, stream)?,
            linear_in: MoshiLinear::unloaded(
                main_dim,
                cfg.dim,
                false,
                Dtype::Float32,
                cfg.quantization,
                stream,
            )?,
            linear_out: MoshiLinear::unloaded(
                cfg.dim,
                audio_vocab - 1,
                false,
                Dtype::Float32,
                cfg.quantization,
                stream,
            )?,
            transformer: MoshiTransformer::unloaded(cfg, stream)?,
        })
    }
}

#[derive(Debug, Clone, ModuleParameters)]
struct DepFormer {
    #[param]
    slices: Vec<DepFormerSlice>,
}

/// Stateful caches for temporal and within-frame depth inference.
#[derive(Debug, Clone)]
pub struct MoshiCache {
    temporal: Vec<ConcatKeyValueCache>,
    depth: Vec<ConcatKeyValueCache>,
}

impl MoshiCache {
    /// Clears both temporal history and the current depth frame.
    pub fn reset(&mut self) {
        self.temporal.iter_mut().for_each(|cache| cache.clear());
        self.depth.iter_mut().for_each(|cache| cache.clear());
    }

    fn reset_depth(&mut self) {
        self.depth.iter_mut().for_each(|cache| cache.clear());
    }
}

/// Logits and hidden state produced for one teacher-forced Moshi frame.
pub struct TokenStepOutput {
    /// Sum of text and audio embeddings entering the temporal transformer.
    pub temporal_input: Array,
    /// Intermediate states from each temporal transformer layer.
    pub temporal_layer_traces: Vec<TemporalLayerTrace>,
    /// Temporal text logits, shaped `[batch, 1, text_card]`.
    pub text_logits: Array,
    /// One audio-logit tensor per generated codebook.
    pub audio_logits: Vec<Array>,
    /// Normalized temporal hidden state consumed by the depth transformer.
    pub temporal_output: Array,
}

/// Sampled text and generated-audio tokens for one model step.
pub struct SampleStepOutput {
    /// Sampled text token, shaped `[batch, 1]`.
    pub text_token: Array,
    /// Sampled generated-codebook tokens, shaped `[batch, dep_q]`.
    pub audio_tokens: Array,
    /// Raw logits retained for parity inspection.
    pub logits: TokenStepOutput,
}

/// Greedy specialization of [`SampleStepOutput`].
pub type GreedyStepOutput = SampleStepOutput;

/// Output from one encoded-audio generation step.
pub type GenerationStepOutput = realtime::RealtimeStepOutput;

/// Realtime generation output with the distributions used for its decisions.
///
/// The first PersonaPlex delayed-stream step initializes state and therefore
/// has no logits. Later steps contain one text distribution and one audio
/// distribution per depth codebook.
pub struct GenerationStepWithLogits {
    /// Normal realtime tokens and optional delay-aligned output frame.
    pub output: GenerationStepOutput,
    /// Text logits shaped `[batch, 1, text_card]`, absent during initialization.
    pub text_logits: Option<Array>,
    /// Audio logits ordered by depth codebook.
    pub audio_logits: Vec<Array>,
}

/// Delayed-stream state for an encoded-audio Moshi inference session.
///
/// Input frames contain only the caller/user side of the Mimi stream. The
/// generated side, temporal/depth caches, text feedback, and per-codebook
/// delays remain internal to this state.
pub struct GenerationState {
    cache: MoshiCache,
    frames: Vec<Vec<Option<Array>>>,
    previous_text: Option<Array>,
    step: usize,
}

impl GenerationState {
    /// Creates an empty encoded-audio generation session.
    pub fn new(model: &Model) -> Self {
        Self {
            cache: model.new_cache(),
            frames: Vec::new(),
            previous_text: None,
            step: 0,
        }
    }

    /// Number of encoded input frames consumed by this session.
    pub fn step(&self) -> usize {
        self.step
    }
}

/// Text tokens and delay-aligned Mimi tokens from offline generation.
pub type EncodedAudioOutput = realtime::EncodedAudioOutput;

/// Intermediate states retained for temporal-layer parity diagnostics.
pub struct TemporalLayerTrace {
    /// First RMS normalization output.
    pub norm1: Array,
    /// Fused QKV projection before head reshaping.
    pub attention_in_proj: Array,
    /// Query heads after rotary position encoding.
    pub attention_queries: Array,
    /// Current key heads after rotary position encoding.
    pub attention_keys: Array,
    /// Cached values supplied to scaled dot-product attention.
    pub attention_values: Array,
    /// Attention result after merging heads and before output projection.
    pub attention_attended: Array,
    /// Self-attention projection before the residual add.
    pub attention: Array,
    /// Residual state after self attention.
    pub post_attention: Array,
    /// Second RMS normalization output.
    pub norm2: Array,
    /// Gated MLP projection before the residual add.
    pub mlp: Array,
    /// Final layer residual state.
    pub output: Array,
}

/// Moshi temporal/depth token language model.
#[derive(Debug, Clone, ModuleParameters)]
pub struct Model {
    /// Parsed model configuration.
    pub args: ModelArgs,
    #[param]
    transformer: MoshiTransformer,
    #[param]
    depformer: DepFormer,
    #[param]
    text_emb: ScaledEmbedding,
    #[param]
    out_norm: nn::RmsNorm,
    #[param]
    text_linear: MoshiLinear,
    #[param]
    audio_embs: Vec<ScaledEmbedding>,
}

impl Model {
    /// Creates an unloaded Moshi model from an MLX-format config.
    pub fn new(args: ModelArgs, stream: &Stream) -> Result<Self, Error> {
        args.validate()?;
        let temporal_cfg = TransformerConfig {
            dim: args.dim,
            num_heads: args.num_heads,
            num_layers: args.num_layers,
            feed_forward: args.dim_feedforward.unwrap_or(4 * args.dim),
            context: args.context,
            max_period: args.max_period,
            rope: true,
            quantization: args.quantization,
        };
        let depth_cfg = TransformerConfig {
            dim: args.depformer_dim,
            num_heads: args.depformer_num_heads,
            num_layers: args.depformer_num_layers,
            feed_forward: args
                .depformer_dim_feedforward
                .unwrap_or(4 * args.depformer_dim),
            context: args.depformer_context.unwrap_or(args.dep_q),
            max_period: args.depformer_max_period.unwrap_or(8.0),
            rope: false,
            quantization: args.quantization,
        };
        let mut slices = Vec::with_capacity(args.dep_q as usize);
        for index in 0..args.dep_q {
            let input_vocab = if index == 0 {
                args.text_card + 1
            } else {
                args.card + 1
            };
            slices.push(DepFormerSlice::unloaded(
                input_vocab,
                args.dim,
                depth_cfg,
                args.card + 1,
                stream,
            )?);
        }
        let audio_embs = (0..args.n_q)
            .map(|_| ScaledEmbedding::unloaded(args.card + 1, args.dim, args.quantization, stream))
            .collect::<Result<_, _>>()?;
        Ok(Self {
            transformer: MoshiTransformer::unloaded(temporal_cfg, stream)?,
            depformer: DepFormer { slices },
            text_emb: ScaledEmbedding::unloaded(
                args.text_card + 1,
                args.dim,
                args.quantization,
                stream,
            )?,
            out_norm: nn::RmsNorm::unloaded(args.dim, RMS_NORM_EPS, Dtype::Float32, stream)?,
            text_linear: MoshiLinear::unloaded(
                args.dim,
                args.text_card,
                false,
                Dtype::Float32,
                args.quantization,
                stream,
            )?,
            audio_embs,
            args,
        })
    }

    /// Allocates empty temporal and depth caches.
    pub fn new_cache(&self) -> MoshiCache {
        MoshiCache {
            temporal: vec![
                ConcatKeyValueCache::new_with_max_size_and_step(
                    self.args.context + 1,
                    256
                );
                self.args.num_layers as usize
            ],
            depth: vec![ConcatKeyValueCache::new(); self.args.depformer_num_layers as usize],
        }
    }

    fn temporal_input(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        stream: &Stream,
    ) -> Result<Array, Exception> {
        if text_token.shape().len() != 2 || text_token.dim(1) != 1 {
            return Err(Exception::custom(
                "Moshi text input must have shape [batch, 1]",
            ));
        }
        if audio_tokens.shape().len() != 2
            || audio_tokens.dim(0) != text_token.dim(0)
            || audio_tokens.dim(1) != self.args.n_q
        {
            return Err(Exception::custom(format!(
                "Moshi audio input must have shape [batch, {}]",
                self.args.n_q
            )));
        }
        let mut x = self.text_emb.forward(text_token, stream)?;
        for (index, emb) in self.audio_embs.iter_mut().enumerate() {
            let token = audio_tokens
                .try_index_device((.., index as i32), stream)?
                .expand_dims(1, stream)?;
            x = x.add(emb.forward(&token, stream)?, stream)?;
        }
        Ok(x)
    }

    fn temporal_input_nonnegative(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        stream: &Stream,
    ) -> Result<Array, Exception> {
        if text_token.shape().len() != 2 || text_token.dim(1) != 1 {
            return Err(Exception::custom(
                "Moshi text input must have shape [batch, 1]",
            ));
        }
        if audio_tokens.shape().len() != 2
            || audio_tokens.dim(0) != text_token.dim(0)
            || audio_tokens.dim(1) != self.args.n_q
        {
            return Err(Exception::custom(format!(
                "Moshi audio input must have shape [batch, {}]",
                self.args.n_q
            )));
        }
        let mut x = self.text_emb.forward_nonnegative(text_token, stream)?;
        for codebook in 0..self.args.n_q {
            let token = audio_tokens
                .try_index_device((.., codebook), stream)?
                .expand_dims(1, stream)?;
            let embedding =
                self.audio_embs[codebook as usize].forward_nonnegative(&token, stream)?;
            x = x.add(embedding, stream)?;
        }
        Ok(x)
    }

    fn temporal_step(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<TemporalStepOutput, Exception> {
        let x = self.temporal_input(text_token, audio_tokens, stream)?;
        let temporal_input = x.clone();
        let (hidden, layer_traces) =
            self.transformer
                .forward_traced(x, &mut cache.temporal, stream)?;
        let hidden = self.out_norm.forward(&hidden, stream)?;
        let logits = self.text_linear.forward(&hidden, stream)?;
        Ok(TemporalStepOutput {
            input: temporal_input,
            layer_traces,
            output: hidden,
            logits,
        })
    }

    fn temporal_step_untraced(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<(Array, Array), Exception> {
        let x = self.temporal_input_nonnegative(text_token, audio_tokens, stream)?;
        let hidden = self.transformer.forward(x, &mut cache.temporal, stream)?;
        let hidden = self.out_norm.forward(&hidden, stream)?;
        let logits = self.text_linear.forward(&hidden, stream)?;
        Ok((hidden, logits))
    }

    fn depth_teacher_forced(
        &mut self,
        temporal_output: &Array,
        depth_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<Vec<Array>, Exception> {
        if depth_tokens.shape().len() != 2
            || depth_tokens.dim(0) != temporal_output.dim(0)
            || depth_tokens.dim(1) != self.args.dep_q
        {
            return Err(Exception::custom(format!(
                "Moshi depth input must have shape [batch, {}] (text then prior audio tokens)",
                self.args.dep_q
            )));
        }
        cache.reset_depth();
        let mut logits = Vec::with_capacity(self.args.dep_q as usize);
        for (index, slice) in self.depformer.slices.iter_mut().enumerate() {
            let token = depth_tokens
                .try_index_device((.., index as i32), stream)?
                .expand_dims(1, stream)?;
            let x = slice
                .linear_in
                .forward(temporal_output, stream)?
                .add(slice.emb.forward(&token, stream)?, stream)?;
            let x = slice.transformer.forward(x, &mut cache.depth, stream)?;
            logits.push(slice.linear_out.forward(&x, stream)?);
        }
        Ok(logits)
    }

    /// Runs one frame using teacher-forced depth inputs.
    ///
    /// `text_token` is `[batch, 1]`, `audio_tokens` is `[batch, n_q]`, and
    /// `depth_tokens` is `[batch, dep_q]`: sampled text followed by the first
    /// `dep_q - 1` generated audio tokens. This layout mirrors `moshi_mlx`'s
    /// slice-by-slice depth loop.
    pub fn token_step(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        depth_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<TokenStepOutput, Exception> {
        let temporal = self.temporal_step(text_token, audio_tokens, cache, stream)?;
        let audio_logits =
            self.depth_teacher_forced(&temporal.output, depth_tokens, cache, stream)?;
        Ok(TokenStepOutput {
            temporal_input: temporal.input,
            temporal_layer_traces: temporal.layer_traces,
            text_logits: temporal.logits,
            audio_logits,
            temporal_output: temporal.output,
        })
    }

    /// Runs one frame with caller-provided text and audio samplers.
    #[allow(clippy::too_many_arguments)]
    pub fn sample_step<TS: Sampler, AS: Sampler>(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        cache: &mut MoshiCache,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        prng_state: Option<&mut RandomState>,
        stream: &Stream,
    ) -> Result<SampleStepOutput, Exception> {
        let temporal = self.temporal_step(text_token, audio_tokens, cache, stream)?;
        let (text, audio_tokens, audio_logits) = self.sample_temporal_output(
            &temporal.output,
            &temporal.logits,
            cache,
            text_sampler,
            audio_samplers,
            text_temperature,
            audio_temperature,
            prng_state,
            stream,
        )?;
        Ok(SampleStepOutput {
            text_token: text,
            audio_tokens,
            logits: TokenStepOutput {
                temporal_input: temporal.input,
                temporal_layer_traces: temporal.layer_traces,
                text_logits: temporal.logits,
                audio_logits,
                temporal_output: temporal.output,
            },
        })
    }

    #[allow(clippy::too_many_arguments)]
    fn sample_temporal_output<TS: Sampler, AS: Sampler>(
        &mut self,
        temporal_output: &Array,
        text_logits: &Array,
        cache: &mut MoshiCache,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        mut prng_state: Option<&mut RandomState>,
        stream: &Stream,
    ) -> Result<(Array, Array, Vec<Array>), Exception> {
        self.sample_temporal_output_forced(
            temporal_output,
            text_logits,
            cache,
            text_sampler,
            audio_samplers,
            text_temperature,
            audio_temperature,
            None,
            None,
            None,
            prng_state.as_deref_mut(),
            false,
            stream,
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn sample_temporal_output_forced<TS: Sampler, AS: Sampler>(
        &mut self,
        temporal_output: &Array,
        text_logits: &Array,
        cache: &mut MoshiCache,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        forced_text_token: Option<&Array>,
        forced_audio_tokens: Option<&Array>,
        forced_audio_codebooks: Option<&[bool]>,
        mut prng_state: Option<&mut RandomState>,
        retain_forced_logits: bool,
        stream: &Stream,
    ) -> Result<(Array, Array, Vec<Array>), Exception> {
        if audio_samplers.len() != self.args.dep_q as usize {
            return Err(Exception::custom(format!(
                "Moshi requires one audio sampler per generated codebook (expected {}, got {})",
                self.args.dep_q,
                audio_samplers.len()
            )));
        }
        let sampled_text = text_sampler.sample(
            text_logits,
            text_temperature,
            prng_state.as_deref_mut(),
            stream,
        )?;
        let text = match forced_text_token {
            Some(token) => {
                if token.shape() != sampled_text.shape() {
                    return Err(Exception::custom(format!(
                        "Moshi forced text token must have shape {:?}, got {:?}",
                        sampled_text.shape(),
                        token.shape()
                    )));
                }
                token.clone()
            }
            None => sampled_text,
        };
        if let Some(tokens) = forced_audio_tokens {
            if tokens.shape().len() != 2
                || tokens.dim(0) != text.dim(0)
                || tokens.dim(1) != self.args.dep_q
            {
                return Err(Exception::custom(format!(
                    "Moshi forced depth tokens must have shape [batch, {}], got {:?}",
                    self.args.dep_q,
                    tokens.shape()
                )));
            }
        }
        if let Some(mask) = forced_audio_codebooks {
            if mask.len() != self.args.dep_q as usize {
                return Err(Exception::custom(format!(
                    "Moshi forced depth mask must have {} entries, got {}",
                    self.args.dep_q,
                    mask.len()
                )));
            }
        }
        cache.reset_depth();
        let mut previous = text.clone();
        let mut predicted = Vec::with_capacity(self.args.dep_q as usize);
        let mut audio_logits = Vec::with_capacity(self.args.dep_q as usize);
        for (index, (slice, sampler)) in self
            .depformer
            .slices
            .iter_mut()
            .zip(audio_samplers.iter_mut())
            .enumerate()
        {
            if let (Some(tokens), Some(mask)) = (forced_audio_tokens, forced_audio_codebooks) {
                if !retain_forced_logits
                    && mask[index]
                    && mask[index..].iter().all(|forced| *forced)
                {
                    for tail in index..self.args.dep_q as usize {
                        predicted.push(tokens.try_index_device((.., tail as i32), stream)?);
                    }
                    break;
                }
            }
            let x = slice
                .linear_in
                .forward(temporal_output, stream)?
                .add(slice.emb.forward_nonnegative(&previous, stream)?, stream)?;
            let x = slice.transformer.forward(x, &mut cache.depth, stream)?;
            let forced_token = match (forced_audio_tokens, forced_audio_codebooks) {
                (Some(tokens), Some(mask)) if mask[index] => {
                    Some(tokens.try_index_device((.., index as i32), stream)?)
                }
                _ => None,
            };
            if let Some(token) = &forced_token {
                if !retain_forced_logits {
                    previous = token.expand_dims(1, stream)?;
                    predicted.push(token.clone());
                    continue;
                }
            }
            let logits = slice.linear_out.forward(&x, stream)?;
            if retain_forced_logits {
                audio_logits.push(logits.clone());
            }
            if let Some(token) = forced_token {
                previous = token.expand_dims(1, stream)?;
                predicted.push(token);
                continue;
            }
            let sampled = sampler.sample(
                &logits,
                audio_temperature,
                prng_state.as_deref_mut(),
                stream,
            )?;
            previous = sampled;
            predicted.push(previous.squeeze_axes(&[-1], stream)?);
            if !retain_forced_logits {
                audio_logits.push(logits);
            }
        }
        let audio_tokens = safemlx::ops::stack_axis(&predicted, 1, stream)?;
        Ok((text, audio_tokens, audio_logits))
    }

    /// Runs one frame with greedy text and audio-codebook sampling.
    pub fn greedy_step(
        &mut self,
        text_token: &Array,
        audio_tokens: &Array,
        cache: &mut MoshiCache,
        stream: &Stream,
    ) -> Result<GreedyStepOutput, Exception> {
        let mut text_sampler = DefaultSampler;
        let mut audio_samplers = (0..self.args.dep_q)
            .map(|_| DefaultSampler)
            .collect::<Vec<_>>();
        self.sample_step(
            text_token,
            audio_tokens,
            cache,
            &mut text_sampler,
            &mut audio_samplers,
            0.0,
            0.0,
            None,
            stream,
        )
    }

    /// Consumes one Mimi input-side frame and advances delayed-stream generation.
    ///
    /// `input_audio_tokens` must be `[batch, n_q - dep_q]`. Supply one sampler
    /// per generated codebook. [`GenerationStepOutput::output_audio_tokens`]
    /// contains a delay-aligned `[batch, dep_q]` frame once one is available.
    #[allow(clippy::too_many_arguments)]
    pub fn generate_step<TS: Sampler, AS: Sampler>(
        &mut self,
        state: &mut GenerationState,
        input_audio_tokens: &Array,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        prng_state: Option<&mut RandomState>,
        stream: &Stream,
    ) -> Result<GenerationStepOutput, Exception> {
        self.generate_step_forced(
            state,
            input_audio_tokens,
            None,
            None,
            text_sampler,
            audio_samplers,
            text_temperature,
            audio_temperature,
            prng_state,
            stream,
        )
    }

    /// Consumes one encoded input-side frame with optional forced agent outputs.
    ///
    /// This is useful for realtime models that prefill prompt segments by
    /// forcing generated-side audio tokens and/or agent text. Forced generated
    /// audio is shaped `[batch, generated_audio_codebooks]`.
    #[allow(clippy::too_many_arguments)]
    pub fn generate_step_forced<TS: Sampler, AS: Sampler>(
        &mut self,
        state: &mut GenerationState,
        input_audio_tokens: &Array,
        forced_generated_audio_tokens: Option<&Array>,
        forced_text_token: Option<&Array>,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        prng_state: Option<&mut RandomState>,
        stream: &Stream,
    ) -> Result<GenerationStepOutput, Exception> {
        Ok(self
            .generate_step_forced_internal(
                state,
                input_audio_tokens,
                forced_generated_audio_tokens,
                forced_text_token,
                text_sampler,
                audio_samplers,
                text_temperature,
                audio_temperature,
                prng_state,
                false,
                stream,
            )?
            .output)
    }

    /// Advances realtime generation and retains the decision logits.
    ///
    /// This diagnostic path supports teacher-forced quantization evaluation;
    /// latency-sensitive callers should continue using [`Self::generate_step`]
    /// or [`Self::generate_step_forced`].
    #[allow(clippy::too_many_arguments)]
    pub fn generate_step_forced_with_logits<TS: Sampler, AS: Sampler>(
        &mut self,
        state: &mut GenerationState,
        input_audio_tokens: &Array,
        forced_generated_audio_tokens: Option<&Array>,
        forced_text_token: Option<&Array>,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        prng_state: Option<&mut RandomState>,
        stream: &Stream,
    ) -> Result<GenerationStepWithLogits, Exception> {
        self.generate_step_forced_internal(
            state,
            input_audio_tokens,
            forced_generated_audio_tokens,
            forced_text_token,
            text_sampler,
            audio_samplers,
            text_temperature,
            audio_temperature,
            prng_state,
            true,
            stream,
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn generate_step_forced_internal<TS: Sampler, AS: Sampler>(
        &mut self,
        state: &mut GenerationState,
        input_audio_tokens: &Array,
        forced_generated_audio_tokens: Option<&Array>,
        forced_text_token: Option<&Array>,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        prng_state: Option<&mut RandomState>,
        retain_forced_logits: bool,
        stream: &Stream,
    ) -> Result<GenerationStepWithLogits, Exception> {
        if self.args.existing_text_padding_id.is_some() && self.args.dep_q == self.args.n_q {
            return self.generate_step_pytorch_style_with_logits(
                state,
                input_audio_tokens,
                forced_generated_audio_tokens,
                forced_text_token,
                text_sampler,
                audio_samplers,
                text_temperature,
                audio_temperature,
                prng_state,
                retain_forced_logits,
                stream,
            );
        }
        let input_codebooks = self.args.input_audio_codebooks();
        if input_audio_tokens.shape().len() != 2 || input_audio_tokens.dim(1) != input_codebooks {
            return Err(Exception::custom(format!(
                "Moshi encoded input must have shape [batch, {input_codebooks}], got {:?}",
                input_audio_tokens.shape()
            )));
        }

        let batch = input_audio_tokens.dim(0);
        let generated_codebooks = self.args.generated_audio_codebooks();
        if let Some(tokens) = forced_generated_audio_tokens {
            if tokens.shape().len() != 2
                || tokens.dim(0) != batch
                || tokens.dim(1) != generated_codebooks
            {
                return Err(Exception::custom(format!(
                    "Moshi forced generated audio must have shape [batch, {generated_codebooks}], got {:?}",
                    tokens.shape()
                )));
            }
        }
        let mut frame = vec![None; self.args.n_q as usize];
        for codebook in 0..input_codebooks {
            frame[(generated_codebooks + codebook) as usize] = Some(
                input_audio_tokens
                    .try_index_device((.., codebook), stream)?
                    .expand_dims(1, stream)?,
            );
        }
        if let Some(tokens) = forced_generated_audio_tokens {
            for codebook in 0..generated_codebooks {
                frame[codebook as usize] = Some(
                    tokens
                        .try_index_device((.., codebook), stream)?
                        .expand_dims(1, stream)?,
                );
            }
        }
        state.frames.push(frame);

        let padding = Array::full::<i32>(
            &[batch, 1],
            Array::from_int(self.args.audio_padding_token()),
            stream,
        )?;
        let mut delayed = Vec::with_capacity(self.args.n_q as usize);
        for (codebook, &delay) in self.args.audio_delays().iter().enumerate() {
            let source = state.step as isize - 1 - delay as isize;
            if source < 0 {
                delayed.push(padding.clone());
                continue;
            }
            let token = state.frames[source as usize][codebook]
                .as_ref()
                .ok_or_else(|| {
                    Exception::custom(format!(
                        "Moshi delayed stream is missing codebook {codebook} at frame {source}"
                    ))
                })?
                .clone();
            delayed.push(token);
        }
        let delayed = safemlx::ops::concatenate_axis(&delayed, 1, stream)?;
        let text_input = match &state.previous_text {
            Some(token) => token.clone(),
            None => Array::full::<i32>(
                &[batch, 1],
                Array::from_int(self.args.text_padding_token()),
                stream,
            )?,
        };
        let (temporal_output, text_logits) =
            self.temporal_step_untraced(&text_input, &delayed, &mut state.cache, stream)?;
        let mut forced_depth_tokens = Vec::new();
        let mut forced_depth_mask = vec![false; self.args.dep_q as usize];
        if forced_generated_audio_tokens.is_some() || self.args.dep_q > generated_codebooks {
            for codebook in 0..self.args.dep_q {
                if codebook < generated_codebooks {
                    match forced_generated_audio_tokens {
                        Some(tokens) => {
                            forced_depth_tokens
                                .push(tokens.try_index_device((.., codebook), stream)?);
                            forced_depth_mask[codebook as usize] = true;
                        }
                        None => forced_depth_tokens.push(Array::zeros::<i32>(&[batch], stream)?),
                    }
                } else {
                    let input_index = codebook - generated_codebooks;
                    if input_index < input_codebooks {
                        forced_depth_tokens
                            .push(input_audio_tokens.try_index_device((.., input_index), stream)?);
                        forced_depth_mask[codebook as usize] = true;
                    } else {
                        forced_depth_tokens.push(Array::zeros::<i32>(&[batch], stream)?);
                    }
                }
            }
        }
        let forced_depth_tokens = if forced_depth_tokens.is_empty() {
            None
        } else {
            Some(safemlx::ops::stack_axis(&forced_depth_tokens, 1, stream)?)
        };
        let (text_token, sampled_audio_tokens, audio_logits) = self.sample_temporal_output_forced(
            &temporal_output,
            &text_logits,
            &mut state.cache,
            text_sampler,
            audio_samplers,
            text_temperature,
            audio_temperature,
            forced_text_token,
            forced_depth_tokens.as_ref(),
            forced_depth_tokens
                .as_ref()
                .map(|_| forced_depth_mask.as_slice()),
            prng_state,
            retain_forced_logits,
            stream,
        )?;

        for (codebook, &delay) in self
            .args
            .audio_delays()
            .iter()
            .take(self.args.generated_audio_codebooks() as usize)
            .enumerate()
        {
            let target = state.step as isize - delay as isize;
            if target >= 0 {
                state.frames[target as usize][codebook] = Some(
                    forced_generated_audio_tokens
                        .unwrap_or(&sampled_audio_tokens)
                        .try_index_device((.., codebook as i32), stream)?
                        .expand_dims(1, stream)?,
                );
            }
        }

        let max_delay = self.args.audio_delays().iter().copied().max().unwrap_or(0) as usize;
        let output_index = state.step.checked_sub(max_delay);
        let output_audio_tokens = output_index
            .map(|index| {
                let tokens = state.frames[index]
                    .iter()
                    .take(self.args.generated_audio_codebooks() as usize)
                    .map(|token| {
                        token.clone().ok_or_else(|| {
                            Exception::custom(format!(
                                "Moshi generated stream is incomplete at frame {index}"
                            ))
                        })
                    })
                    .collect::<Result<Vec<_>, _>>()?;
                safemlx::ops::concatenate_axis(&tokens, 1, stream)
            })
            .transpose()?;

        state.previous_text = Some(text_token.clone());
        state.step += 1;
        Ok(GenerationStepWithLogits {
            output: GenerationStepOutput {
                text_token,
                sampled_audio_tokens,
                output_audio_tokens,
            },
            text_logits: Some(text_logits),
            audio_logits,
        })
    }

    /// Greedily generates delay-aligned Mimi tokens from an encoded input sequence.
    ///
    /// Input and output use Mimi's `[batch, codebooks, frames]` layout. This
    /// method does not append encoded silence, so delayed tail frames are not
    /// flushed after the supplied input ends.
    pub fn generate_encoded_greedy(
        &mut self,
        input_audio_tokens: &Array,
        stream: &Stream,
    ) -> Result<EncodedAudioOutput, Exception> {
        let input_codebooks = self.args.input_audio_codebooks();
        if input_audio_tokens.shape().len() != 3 || input_audio_tokens.dim(1) != input_codebooks {
            return Err(Exception::custom(format!(
                "Moshi encoded input sequence must have shape [batch, {input_codebooks}, frames], got {:?}",
                input_audio_tokens.shape()
            )));
        }
        let batch = input_audio_tokens.dim(0);
        let mut state = GenerationState::new(self);
        let mut text_sampler = DefaultSampler;
        let mut audio_samplers = (0..self.args.dep_q)
            .map(|_| DefaultSampler)
            .collect::<Vec<_>>();
        let mut text = Vec::with_capacity(input_audio_tokens.dim(2) as usize);
        let mut audio = Vec::new();
        for frame in 0..input_audio_tokens.dim(2) {
            let input = input_audio_tokens.try_index_device((.., .., frame), stream)?;
            let output = self.generate_step(
                &mut state,
                &input,
                &mut text_sampler,
                &mut audio_samplers,
                0.0,
                0.0,
                None,
                stream,
            )?;
            text.push(output.text_token.squeeze_axes(&[-1], stream)?);
            if let Some(tokens) = output.output_audio_tokens {
                audio.push(tokens);
            }
        }
        let text_tokens = if text.is_empty() {
            Array::zeros::<i32>(&[batch, 0], stream)?
        } else {
            safemlx::ops::stack_axis(&text, 1, stream)?
        };
        let audio_tokens = if audio.is_empty() {
            Array::zeros::<i32>(&[batch, self.args.generated_audio_codebooks(), 0], stream)?
        } else {
            safemlx::ops::stack_axis(&audio, 2, stream)?
        };
        Ok(EncodedAudioOutput {
            text_tokens,
            audio_tokens,
        })
    }

    #[allow(clippy::too_many_arguments)]
    fn generate_step_pytorch_style_with_logits<TS: Sampler, AS: Sampler>(
        &mut self,
        state: &mut GenerationState,
        input_audio_tokens: &Array,
        forced_generated_audio_tokens: Option<&Array>,
        forced_text_token: Option<&Array>,
        text_sampler: &mut TS,
        audio_samplers: &mut [AS],
        text_temperature: f32,
        audio_temperature: f32,
        prng_state: Option<&mut RandomState>,
        retain_forced_logits: bool,
        stream: &Stream,
    ) -> Result<GenerationStepWithLogits, Exception> {
        let input_codebooks = self.args.input_audio_codebooks();
        if input_audio_tokens.shape().len() != 2 || input_audio_tokens.dim(1) != input_codebooks {
            return Err(Exception::custom(format!(
                "Moshi encoded input must have shape [batch, {input_codebooks}], got {:?}",
                input_audio_tokens.shape()
            )));
        }

        let batch = input_audio_tokens.dim(0);
        let generated_codebooks = self.args.generated_audio_codebooks();
        if let Some(tokens) = forced_generated_audio_tokens {
            if tokens.shape().len() != 2
                || tokens.dim(0) != batch
                || tokens.dim(1) != generated_codebooks
            {
                return Err(Exception::custom(format!(
                    "Moshi forced generated audio must have shape [batch, {generated_codebooks}], got {:?}",
                    tokens.shape()
                )));
            }
        }
        if let Some(token) = forced_text_token {
            if token.shape().len() != 2 || token.dim(0) != batch || token.dim(1) != 1 {
                return Err(Exception::custom(format!(
                    "Moshi forced text token must have shape [batch, 1], got {:?}",
                    token.shape()
                )));
            }
        }

        let slots = self.args.n_q as usize + 1;
        let offset = state.step;
        for codebook in 0..input_codebooks {
            let audio_slot = 1 + generated_codebooks + codebook;
            let delay = self.args.delays[audio_slot as usize] as usize;
            let position = offset + delay;
            ensure_token_position(&mut state.frames, position, slots);
            state.frames[position][audio_slot as usize] = Some(
                input_audio_tokens
                    .try_index_device((.., codebook), stream)?
                    .expand_dims(1, stream)?,
            );
        }
        if let Some(tokens) = forced_generated_audio_tokens {
            for codebook in 0..generated_codebooks {
                let audio_slot = 1 + codebook;
                let delay = self.args.delays[audio_slot as usize] as usize;
                let position = offset + delay;
                ensure_token_position(&mut state.frames, position, slots);
                state.frames[position][audio_slot as usize] = Some(
                    tokens
                        .try_index_device((.., codebook), stream)?
                        .expand_dims(1, stream)?,
                );
            }
        }
        if let Some(token) = forced_text_token {
            let delay = self.args.delays[0] as usize;
            let position = offset + delay;
            ensure_token_position(&mut state.frames, position, slots);
            state.frames[position][0] = Some(token.clone());
        }

        ensure_token_position(&mut state.frames, offset, slots);
        for (slot, &delay) in self.args.delays.iter().enumerate() {
            if offset <= delay as usize {
                let token = if slot == 0 {
                    Array::full::<i32>(&[batch, 1], Array::from_int(self.args.text_card), stream)?
                } else {
                    Array::full::<i32>(
                        &[batch, 1],
                        Array::from_int(self.args.audio_padding_token()),
                        stream,
                    )?
                };
                state.frames[offset][slot] = Some(token);
            }
        }

        if offset == 0 {
            state.step += 1;
            return Ok(GenerationStepWithLogits {
                output: GenerationStepOutput {
                    text_token: Array::full::<i32>(
                        &[batch, 1],
                        Array::from_int(self.args.text_card),
                        stream,
                    )?,
                    sampled_audio_tokens: Array::full::<i32>(
                        &[batch, self.args.dep_q],
                        Array::from_int(self.args.audio_padding_token()),
                        stream,
                    )?,
                    output_audio_tokens: None,
                },
                text_logits: None,
                audio_logits: Vec::new(),
            });
        }

        let model_input_position = offset - 1;
        let target_position = offset;
        let text_input = token_position(&state.frames, model_input_position, 0)?;
        let mut audio_inputs = Vec::with_capacity(self.args.n_q as usize);
        for slot in 1..=self.args.n_q as usize {
            audio_inputs.push(token_position(&state.frames, model_input_position, slot)?);
        }
        let audio_input = safemlx::ops::concatenate_axis(&audio_inputs, 1, stream)?;
        let (temporal_output, text_logits) =
            self.temporal_step_untraced(&text_input, &audio_input, &mut state.cache, stream)?;

        ensure_token_position(&mut state.frames, target_position, slots);
        let forced_text = state.frames[target_position][0].clone();
        let mut forced_depth_tokens = Vec::with_capacity(self.args.dep_q as usize);
        let mut forced_depth_mask = vec![false; self.args.dep_q as usize];
        for codebook in 0..self.args.dep_q {
            let slot = 1 + codebook as usize;
            if let Some(token) = &state.frames[target_position][slot] {
                forced_depth_tokens.push(token.squeeze_axes(&[-1], stream)?);
                forced_depth_mask[codebook as usize] = true;
            } else {
                forced_depth_tokens.push(Array::zeros::<i32>(&[batch], stream)?);
            }
        }
        let forced_depth_tokens = safemlx::ops::stack_axis(&forced_depth_tokens, 1, stream)?;
        let (text_token, sampled_audio_tokens, audio_logits) = self.sample_temporal_output_forced(
            &temporal_output,
            &text_logits,
            &mut state.cache,
            text_sampler,
            audio_samplers,
            text_temperature,
            audio_temperature,
            forced_text.as_ref(),
            Some(&forced_depth_tokens),
            Some(&forced_depth_mask),
            prng_state,
            retain_forced_logits,
            stream,
        )?;

        if state.frames[target_position][0].is_none() {
            state.frames[target_position][0] = Some(text_token.clone());
        }
        for codebook in 0..self.args.dep_q {
            let slot = 1 + codebook as usize;
            if state.frames[target_position][slot].is_none() {
                state.frames[target_position][slot] = Some(
                    sampled_audio_tokens
                        .try_index_device((.., codebook), stream)?
                        .expand_dims(1, stream)?,
                );
            }
        }

        let max_delay = self.args.delays.iter().copied().max().unwrap_or(0) as usize;
        let output_audio_tokens = if offset <= max_delay {
            None
        } else {
            let base = offset - max_delay;
            let mut tokens = Vec::with_capacity(generated_codebooks as usize);
            for codebook in 0..generated_codebooks {
                let slot = 1 + codebook as usize;
                let position = base + self.args.delays[slot] as usize;
                tokens.push(token_position(&state.frames, position, slot)?);
            }
            Some(safemlx::ops::concatenate_axis(&tokens, 1, stream)?)
        };

        state.previous_text = Some(text_token.clone());
        state.step += 1;
        Ok(GenerationStepWithLogits {
            output: GenerationStepOutput {
                text_token,
                sampled_audio_tokens,
                output_audio_tokens,
            },
            text_logits: Some(text_logits),
            audio_logits,
        })
    }
}

fn ensure_token_position(frames: &mut Vec<Vec<Option<Array>>>, position: usize, slots: usize) {
    while frames.len() <= position {
        frames.push(vec![None; slots]);
    }
}

fn token_position(
    frames: &[Vec<Option<Array>>],
    position: usize,
    slot: usize,
) -> Result<Array, Exception> {
    frames
        .get(position)
        .and_then(|frame| frame.get(slot))
        .and_then(|token| token.clone())
        .ok_or_else(|| {
            Exception::custom(format!(
                "Moshi delayed stream is missing slot {slot} at position {position}"
            ))
        })
}

impl RealtimeSpeechModel for Model {
    type State = GenerationState;

    fn realtime_config(&self) -> RealtimeSpeechConfig<'_> {
        RealtimeSpeechConfig {
            total_audio_codebooks: self.args.n_q,
            input_audio_codebooks: self.args.input_audio_codebooks(),
            generated_audio_codebooks: self.args.generated_audio_codebooks(),
            depth_audio_codebooks: self.args.dep_q,
            text_padding_token: self.args.text_padding_token(),
            audio_padding_token: self.args.audio_padding_token(),
            audio_delays: self.args.audio_delays(),
        }
    }

    fn new_realtime_state(&self) -> Self::State {
        GenerationState::new(self)
    }

    fn step_realtime<TS, AS>(
        &mut self,
        state: &mut Self::State,
        input: RealtimeStepInput<'_>,
        sampling: RealtimeSampling<'_, TS, AS>,
        stream: &Stream,
    ) -> Result<GenerationStepOutput, Exception>
    where
        TS: Sampler,
        AS: Sampler,
    {
        self.generate_step(
            state,
            input.input_audio_tokens,
            sampling.text_sampler,
            sampling.audio_samplers,
            sampling.text_temperature,
            sampling.audio_temperature,
            sampling.prng_state,
            stream,
        )
    }
}

struct TemporalStepOutput {
    input: Array,
    layer_traces: Vec<TemporalLayerTrace>,
    output: Array,
    logits: Array,
}

/// Reads and validates a Moshi MLX `config.json`.
///
/// When the file is absent, this returns [`ModelArgs::v0_1`], matching the
/// behavior used by `moshi_mlx` for the original Moshika/Moshiko releases.
pub fn get_model_args(model_dir: impl AsRef<Path>) -> Result<ModelArgs, Error> {
    let config_path = model_dir.as_ref().join("config.json");
    let args: ModelArgs = if config_path.exists() {
        serde_json::from_reader(std::fs::File::open(config_path)?)?
    } else {
        ModelArgs::v0_1()
    };
    args.validate()?;
    Ok(args)
}

/// Loads a dense or MLX affine-quantized Moshi checkpoint for token-only inference.
pub fn load_model(
    model_dir: impl AsRef<Path>,
    stream: &Stream,
    weights_stream: &Stream,
) -> Result<Model, Error> {
    let model_dir = model_dir.as_ref();
    let args = get_model_args(model_dir)?;
    let weights_name = args
        .moshi_name
        .clone()
        .unwrap_or_else(|| "model.safetensors".to_string());
    let mut model = Model::new(args, stream)?;
    let config = StrictLoadConfig::default();
    let mut report = StrictLoadReport::default();
    if weights_name == "model.safetensors"
        && model_dir.join("model.safetensors.index.json").exists()
    {
        load_safetensors_dir_strict(&mut model, model_dir, weights_stream, &config, &mut report)?;
    } else {
        load_safetensors_strict(
            &mut model,
            model_dir.join(&weights_name),
            weights_stream,
            &config,
            &mut report,
        )?;
    }
    report.finish(&model, &config)?;
    model.copy_to_stream(stream)?;
    Ok(model)
}

/// Loads a dense Moshi checkpoint while quantizing each matrix as it is read.
///
/// This is the experimental, no-conversion counterpart to
/// [`crate::quantization::quantize_checkpoint`]. Both paths call the same
/// affine tensor transform and produce the same in-memory parameter layout.
pub fn load_model_quantized(
    model_dir: impl AsRef<Path>,
    quantization: WeightQuantization,
    stream: &Stream,
    weights_stream: &Stream,
) -> Result<Model, Error> {
    let model_dir = model_dir.as_ref();
    let mut args = get_model_args(model_dir)?;
    if !crate::quantization::should_quantize_on_load("Moshi", args.quantization, quantization)? {
        return load_model(model_dir, stream, weights_stream);
    }
    args.quantization = Some(quantization);
    let weights_name = args
        .moshi_name
        .clone()
        .unwrap_or_else(|| "model.safetensors".to_string());
    let mut model = Model::new(args, stream)?;
    let config = StrictLoadConfig::default();
    let mut report = StrictLoadReport::default();
    if weights_name == "model.safetensors"
        && model_dir.join("model.safetensors.index.json").exists()
    {
        for file in crate::weights::safetensors_files(model_dir)? {
            load_safetensors_quantized_strict(
                &mut model,
                file,
                weights_stream,
                stream,
                quantization,
                &config,
                &mut report,
            )?;
        }
    } else {
        load_safetensors_quantized_strict(
            &mut model,
            model_dir.join(weights_name),
            weights_stream,
            stream,
            quantization,
            &config,
            &mut report,
        )?;
    }
    report.finish(&model, &config)?;
    model.copy_to_stream(stream)?;
    Ok(model)
}

/// Loads a PyTorch Moshi-family safetensors checkpoint into this model.
///
/// This supports the public Kyutai/NVIDIA PyTorch Moshi layout, where the
/// depth transformer stores per-codebook `weights_per_step` projections packed
/// along the output dimension. The loader rewrites those tensors into this
/// crate's explicit per-depth-slice parameter tree before strict validation.
pub fn load_pytorch_safetensors_model(
    args: ModelArgs,
    weights_path: impl AsRef<Path>,
    stream: &Stream,
    weights_stream: &Stream,
) -> Result<Model, Error> {
    let mut model = Model::new(args, stream)?;
    load_pytorch_safetensors_strict(&mut model, weights_path, weights_stream)?;
    model.copy_to_stream(stream)?;
    Ok(model)
}

/// Strict-loads one PyTorch Moshi-family safetensors file into an existing model.
pub fn load_pytorch_safetensors_strict(
    model: &mut Model,
    path: impl AsRef<Path>,
    weights_stream: &Stream,
) -> Result<(), Error> {
    load_pytorch_safetensors_files_strict(model, [path.as_ref()], weights_stream)
}

/// Strict-loads one or more PyTorch Moshi-family safetensors shards.
pub fn load_pytorch_safetensors_files_strict<P, I>(
    model: &mut Model,
    paths: I,
    weights_stream: &Stream,
) -> Result<(), Error>
where
    P: AsRef<Path>,
    I: IntoIterator<Item = P>,
{
    let config = StrictLoadConfig::default();
    let mut report = StrictLoadReport::default();
    let args = model.args.clone();
    for path in paths {
        let mut params = model.parameters_mut().flatten();
        for_each_safetensor_array(path.as_ref(), weights_stream, |source_key, value| {
            let transformed = transform_pytorch_tensor(&args, &source_key, value, weights_stream)?;
            for (key, value) in transformed {
                load_array_strict(&mut params, key, value, &config, &mut report);
            }
            Ok(())
        })?;
    }
    report.finish(model, &config)
}

/// Loads dense PyTorch Moshi-family shards while quantizing transformed tensors.
pub fn load_pytorch_safetensors_files_quantized_strict<P, I>(
    model: &mut Model,
    paths: I,
    weights_stream: &Stream,
    quantization_stream: &Stream,
    quantization: WeightQuantization,
) -> Result<(), Error>
where
    P: AsRef<Path>,
    I: IntoIterator<Item = P>,
{
    quantization.validate()?;
    let config = StrictLoadConfig::default();
    let mut report = StrictLoadReport::default();
    let args = model.args.clone();
    for path in paths {
        let mut params = model.parameters_mut().flatten();
        for_each_safetensor_array(path.as_ref(), weights_stream, |source_key, value| {
            let transformed = transform_pytorch_tensor(&args, &source_key, value, weights_stream)?;
            for (key, value) in transformed {
                load_array_quantized_strict(
                    &mut params,
                    key,
                    value,
                    quantization_stream,
                    quantization,
                    &config,
                    &mut report,
                )?;
            }
            Ok(())
        })?;
    }
    report.finish(model, &config)
}

fn transform_pytorch_tensor(
    args: &ModelArgs,
    key: &str,
    value: Array,
    stream: &Stream,
) -> Result<Vec<(String, Array)>, Error> {
    if let Some((index, suffix)) = parse_indexed_tensor(key, "emb") {
        return Ok(vec![(format!("audio_embs.{index}.{suffix}"), value)]);
    }
    if let Some((index, suffix)) = parse_indexed_tensor(key, "depformer_in") {
        return Ok(vec![(
            format!("depformer.slices.{index}.linear_in.{suffix}"),
            value,
        )]);
    }
    if let Some((index, suffix)) = parse_indexed_tensor(key, "linears") {
        return Ok(vec![(
            format!("depformer.slices.{index}.linear_out.{suffix}"),
            value,
        )]);
    }
    if let Some((index, suffix)) = parse_indexed_tensor(key, "depformer_emb") {
        return Ok(vec![(
            format!("depformer.slices.{}.emb.{suffix}", index + 1),
            value,
        )]);
    }
    if let Some(suffix) = key
        .strip_prefix("depformer_text_emb.")
        .and_then(tensor_suffix)
    {
        return Ok(vec![(format!("depformer.slices.0.emb.{suffix}"), value)]);
    }
    if key == "out_norm.alpha" {
        return Ok(vec![(
            "out_norm.weight".to_string(),
            squeeze_norm(value, stream)?,
        )]);
    }
    if let Some((layer, norm)) = parse_norm_alpha(key, "transformer.layers") {
        return Ok(vec![(
            format!("transformer.layers.{layer}.{norm}.weight"),
            squeeze_norm(value, stream)?,
        )]);
    }
    if let Some(rest) = key
        .strip_prefix("transformer.layers.")
        .and_then(|rest| rest.strip_suffix(".self_attn.in_proj_weight"))
    {
        return Ok(vec![(
            format!("transformer.layers.{rest}.self_attn.in_proj.weight"),
            value,
        )]);
    }
    if key.starts_with("text_emb.")
        || key.starts_with("text_linear.")
        || key.starts_with("transformer.layers.")
    {
        return Ok(vec![(key.to_string(), value)]);
    }

    if let Some((layer, norm)) = parse_norm_alpha(key, "depformer.layers") {
        let value = squeeze_norm(value, stream)?;
        let mut out = Vec::with_capacity(args.dep_q as usize);
        for slice in 0..args.dep_q {
            out.push((
                format!("depformer.slices.{slice}.transformer.layers.{layer}.{norm}.weight"),
                value.clone(),
            ));
        }
        return Ok(out);
    }
    if let Some((layer, suffix)) = parse_depformer_attention_weight(key) {
        let mut out = Vec::with_capacity(args.dep_q as usize);
        for slice in 0..args.dep_q {
            out.push((
                format!("depformer.slices.{slice}.transformer.layers.{layer}.self_attn.{suffix}"),
                split_first_axis(&value, args.dep_q, slice, stream)?,
            ));
        }
        return Ok(out);
    }
    if let Some((layer, slice, linear)) = parse_depformer_gating_weight(key) {
        return Ok(vec![(
            format!("depformer.slices.{slice}.transformer.layers.{layer}.gating.{linear}"),
            value,
        )]);
    }

    Ok(vec![(key.to_string(), value)])
}

fn squeeze_norm(value: Array, stream: &Stream) -> Result<Array, Exception> {
    let dim = value.dim(-1);
    value.reshape(&[dim], stream)
}

fn split_first_axis(
    value: &Array,
    parts: i32,
    index: i32,
    stream: &Stream,
) -> Result<Array, Exception> {
    let rows = value.dim(0);
    if rows % parts != 0 {
        return Err(Exception::custom(format!(
            "cannot split tensor with first dimension {rows} into {parts} parts"
        )));
    }
    let chunk = rows / parts;
    let start = index * chunk;
    let end = start + chunk;
    value.try_index_device((start..end, ..), stream)
}

fn tensor_suffix(suffix: &str) -> Option<&str> {
    matches!(suffix, "weight" | "scales" | "biases").then_some(suffix)
}

fn parse_indexed_tensor<'a>(key: &'a str, prefix: &str) -> Option<(i32, &'a str)> {
    let rest = key.strip_prefix(prefix)?.strip_prefix('.')?;
    let (index, suffix) = rest.split_once('.')?;
    Some((index.parse().ok()?, tensor_suffix(suffix)?))
}

fn parse_norm_alpha(key: &str, prefix: &str) -> Option<(i32, &'static str)> {
    let rest = key.strip_prefix(prefix)?.strip_prefix('.')?;
    let (layer, suffix) = rest.split_once('.')?;
    let norm = match suffix {
        "norm1.alpha" => "norm1",
        "norm2.alpha" => "norm2",
        _ => return None,
    };
    Some((layer.parse().ok()?, norm))
}

fn parse_depformer_attention_weight(key: &str) -> Option<(i32, &'static str)> {
    let rest = key.strip_prefix("depformer.layers.")?;
    let (layer, suffix) = rest.split_once('.')?;
    let suffix = match suffix {
        "self_attn.in_proj_weight" => "in_proj.weight",
        "self_attn.out_proj.weight" => "out_proj.weight",
        "self_attn.in_proj.weight" => "in_proj.weight",
        "self_attn.in_proj.scales" => "in_proj.scales",
        "self_attn.in_proj.biases" => "in_proj.biases",
        "self_attn.out_proj.scales" => "out_proj.scales",
        "self_attn.out_proj.biases" => "out_proj.biases",
        _ => return None,
    };
    Some((layer.parse().ok()?, suffix))
}

fn parse_depformer_gating_weight(key: &str) -> Option<(i32, i32, &'static str)> {
    let rest = key.strip_prefix("depformer.layers.")?;
    let (layer, rest) = rest.split_once(".gating.")?;
    let (slice, suffix) = rest.split_once('.')?;
    let linear = match suffix {
        "linear_in.weight" => "linear_in.weight",
        "linear_out.weight" => "linear_out.weight",
        "linear_in.scales" => "linear_in.scales",
        "linear_in.biases" => "linear_in.biases",
        "linear_out.scales" => "linear_out.scales",
        "linear_out.biases" => "linear_out.biases",
        _ => return None,
    };
    Some((layer.parse().ok()?, slice.parse().ok()?, linear))
}

#[cfg(test)]
mod tests {
    use super::{
        parse_depformer_attention_weight, parse_depformer_gating_weight, Model, ModelArgs,
    };
    use crate::quantization::WeightQuantization;
    use safemlx::{module::ModuleParameters, Device, DeviceType, ExecutionContext};

    fn minimal_config() -> &'static str {
        r#"{
            "dim": 16, "text_card": 32, "n_q": 4, "dep_q": 2, "card": 8,
            "num_heads": 4, "num_layers": 2, "causal": true, "context": 16,
            "max_period": 10000, "positional_embedding": "rope",
            "depformer_dim": 8, "depformer_dim_feedforward": 32,
            "depformer_num_heads": 2, "depformer_num_layers": 2,
            "depformer_context": 2, "depformer_pos_emb": "none",
            "delays": [0, 0, 1, 0, 1]
        }"#
    }

    #[test]
    fn parses_moshi_mlx_config() {
        let args: ModelArgs = serde_json::from_str(minimal_config()).unwrap();
        args.validate().unwrap();
        assert_eq!(args.text_padding_token(), 32);
        assert_eq!(args.audio_padding_token(), 8);
        assert_eq!(args.audio_delays(), &[0, 1, 0, 1]);
    }

    #[test]
    fn rejects_wrong_delay_count() {
        let mut value: serde_json::Value = serde_json::from_str(minimal_config()).unwrap();
        value["delays"] = serde_json::json!([0, 1]);
        let args: ModelArgs = serde_json::from_value(value).unwrap();
        assert!(args.validate().unwrap_err().to_string().contains("delays"));
    }

    #[test]
    fn rejects_negative_delays() {
        let mut value: serde_json::Value = serde_json::from_str(minimal_config()).unwrap();
        value["delays"] = serde_json::json!([0, 0, -1, 0, 1]);
        let args: ModelArgs = serde_json::from_value(value).unwrap();
        assert!(args
            .validate()
            .unwrap_err()
            .to_string()
            .contains("non-negative"));
    }

    #[test]
    fn released_v0_1_config_is_valid() {
        let args = ModelArgs::v0_1();
        args.validate().unwrap();
        assert_eq!(args.delays.len(), 17);
        assert_eq!(args.depformer_dim_feedforward, Some(4096));
    }

    #[test]
    fn mxfp4_realtime_model_tree_omits_affine_biases() {
        let mut value: serde_json::Value = serde_json::from_str(minimal_config()).unwrap();
        value["dim"] = 32.into();
        value["dim_feedforward"] = 64.into();
        value["depformer_dim"] = 32.into();
        value["depformer_dim_feedforward"] = 64.into();
        let mut args: ModelArgs = serde_json::from_value(value).unwrap();
        args.quantization = Some(WeightQuantization::MxFp4);
        let context = ExecutionContext::new(Device::new(DeviceType::Gpu, 0));
        let model = Model::new(args, context.stream()).unwrap();
        let params = model.parameters().flatten();
        assert!(params.contains_key("text_emb.scales"));
        assert!(!params.contains_key("text_emb.biases"));
        assert!(params.contains_key("transformer.layers.0.self_attn.in_proj.scales"));
        assert!(!params.contains_key("transformer.layers.0.self_attn.in_proj.biases"));
        assert_eq!(params["text_emb.scales"].dtype(), safemlx::Dtype::Uint8);
    }

    #[test]
    fn parses_pytorch_moshi_depth_weight_names() {
        assert_eq!(
            parse_depformer_attention_weight("depformer.layers.3.self_attn.in_proj_weight"),
            Some((3, "in_proj.weight"))
        );
        assert_eq!(
            parse_depformer_attention_weight("depformer.layers.3.self_attn.out_proj.weight"),
            Some((3, "out_proj.weight"))
        );
        assert_eq!(
            parse_depformer_gating_weight("depformer.layers.4.gating.15.linear_in.weight"),
            Some((4, 15, "linear_in.weight"))
        );
        assert_eq!(
            parse_depformer_gating_weight("depformer.layers.4.gating.15.linear_out.weight"),
            Some((4, 15, "linear_out.weight"))
        );
    }

    #[test]
    #[ignore = "requires an MLX runtime with a Metal device"]
    fn parameter_names_match_moshi_mlx() {
        let ctx = ExecutionContext::new(Device::new(DeviceType::Cpu, 0));
        let args: ModelArgs = serde_json::from_str(minimal_config()).unwrap();
        let model = Model::new(args, ctx.stream()).unwrap();
        let params = model.parameters().flatten();
        for key in [
            "text_emb.weight",
            "audio_embs.0.weight",
            "out_norm.weight",
            "text_linear.weight",
            "transformer.layers.0.self_attn.in_proj.weight",
            "transformer.layers.0.gating.linear_in.weight",
            "depformer.slices.0.linear_in.weight",
            "depformer.slices.0.transformer.layers.0.norm1.weight",
        ] {
            assert!(params.contains_key(key), "missing parameter key {key}");
        }
    }
}
