// Args:
//     conversation (Union[list[dict[str, str]], list[list[dict[str, str]]]]): A list of dicts
//         with "role" and "content" keys, representing the chat history so far.
//     tools (`list[Union[Dict, Callable]]`, *optional*):
//         A list of tools (callable functions) that will be accessible to the model. If the template does not
//         support function calling, this argument will have no effect. Each tool should be passed as a JSON Schema,
//         giving the name, description and argument types for the tool. See our
//         [chat templating guide](https://huggingface.co/docs/transformers/main/en/chat_templating#automated-function-conversion-for-tool-use)
//         for more information.
//     documents (`list[dict[str, str]]`, *optional*):
//         A list of dicts representing documents that will be accessible to the model if it is performing RAG
//         (retrieval-augmented generation). If the template does not support RAG, this argument will have no
//         effect. We recommend that each document should be a dict containing "title" and "text" keys. Please
//         see the RAG section of the [chat templating guide](https://huggingface.co/docs/transformers/main/en/chat_templating#arguments-for-RAG)
//         for examples of passing documents with chat templates.
//     chat_template (`str`, *optional*):
//         A Jinja template to use for this conversion. It is usually not necessary to pass anything to this
//         argument, as the model's template will be used by default.
//     add_generation_prompt (bool, *optional*):
//         If this is set, a prompt with the token(s) that indicate
//         the start of an assistant message will be appended to the formatted output. This is useful when you want to generate a response from the model.
//         Note that this argument will be passed to the chat template, and so it must be supported in the
//         template for this argument to have any effect.
//     continue_final_message (bool, *optional*):
//         If this is set, the chat will be formatted so that the final
//         message in the chat is open-ended, without any EOS tokens. The model will continue this message
//         rather than starting a new one. This allows you to "prefill" part of
//         the model's response for it. Cannot be used at the same time as `add_generation_prompt`.
//     tokenize (`bool`, defaults to `True`):
//         Whether to tokenize the output. If `False`, the output will be a string.
//     padding (`bool`, `str` or [`~utils.PaddingStrategy`], *optional*, defaults to `False`):
//             Select a strategy to pad the returned sequences (according to the model's padding side and padding
//             index) among:

//         - `True` or `'longest'`: Pad to the longest sequence in the batch (or no padding if only a single
//             sequence if provided).
//         - `'max_length'`: Pad to a maximum length specified with the argument `max_length` or to the maximum
//             acceptable input length for the model if that argument is not provided.
//         - `False` or `'do_not_pad'` (default): No padding (i.e., can output a batch with sequences of different
//             lengths).
//     truncation (`bool`, defaults to `False`):
//         Whether to truncate sequences at the maximum length. Has no effect if tokenize is `False`.
//     max_length (`int`, *optional*):
//         Maximum length (in tokens) to use for padding or truncation. Has no effect if tokenize is `False`. If
//         not specified, the tokenizer's `max_length` attribute will be used as a default.
//     return_tensors (`str` or [`~utils.TensorType`], *optional*):
//         If set, will return tensors of a particular framework. Has no effect if tokenize is `False`. Acceptable
//         values are:
//         - `'tf'`: Return TensorFlow `tf.Tensor` objects.
//         - `'pt'`: Return PyTorch `torch.Tensor` objects.
//         - `'np'`: Return NumPy `np.ndarray` objects.
//         - `'jax'`: Return JAX `jnp.ndarray` objects.
//     return_dict (`bool`, defaults to `False`):
//         Whether to return a dictionary with named outputs. Has no effect if tokenize is `False`.
//     tokenizer_kwargs (`dict[str: Any]`, *optional*): Additional kwargs to pass to the tokenizer.
//     return_assistant_tokens_mask (`bool`, defaults to `False`):
//         Whether to return a mask of the assistant generated tokens. For tokens generated by the assistant,
//         the mask will contain 1. For user and system tokens, the mask will contain 0.
//         This functionality is only available for chat templates that support it via the `{% generation %}` keyword.
//     **kwargs: Additional kwargs to pass to the template renderer. Will be accessible by the chat template.

// Returns:
//     `Union[list[int], Dict]`: A list of token ids representing the tokenized chat so far, including control tokens. This
//     output is ready to pass to the model, either directly or via methods like `generate()`. If `return_dict` is
//     set, will return a dict of tokenizer outputs instead.
// """

use std::{
    collections::{BTreeMap, BTreeSet, HashMap},
    fs::read_to_string,
    ops::{Deref, DerefMut},
    path::Path,
    str::FromStr,
};

use minijinja::{Environment, Template};
use serde::Serialize;
use tokenizers::Encoding;

use crate::error::Error;

const DEFAULT_CHAT_TEMPLATE_NAME: &str = "default";
const TOOL_USE_CHAT_TEMPLATE_NAME: &str = "tool_use";

/// A single chat template or a Hugging Face named-template collection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ModelChatTemplate {
    Single(String),
    Named(BTreeMap<String, String>),
}

impl From<String> for ModelChatTemplate {
    fn from(template: String) -> Self {
        Self::Single(template)
    }
}

impl From<&str> for ModelChatTemplate {
    fn from(template: &str) -> Self {
        Self::Single(template.to_owned())
    }
}

/// Stable identity of the template selected from a checkpoint's template metadata.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum ChatTemplateIdentity {
    Single,
    Named(String),
}

/// A selected Jinja template together with its stable checkpoint-local identity.
#[derive(Debug, Clone)]
pub struct SelectedChatTemplate<'a> {
    template: &'a str,
    identity: ChatTemplateIdentity,
}

impl SelectedChatTemplate<'_> {
    pub fn template(&self) -> &str {
        self.template
    }

    pub fn identity(&self) -> &ChatTemplateIdentity {
        &self.identity
    }
}

impl ModelChatTemplate {
    /// Selects `tool_use` for a non-empty tool list when present, and `default`
    /// otherwise. Single templates are always selected unchanged.
    pub fn select(
        &self,
        tools: Option<&[serde_json::Value]>,
    ) -> Result<SelectedChatTemplate<'_>, Error> {
        match self {
            Self::Single(template) => Ok(SelectedChatTemplate {
                template,
                identity: ChatTemplateIdentity::Single,
            }),
            Self::Named(templates) => {
                let selected_name = if tools.is_some_and(|tools| !tools.is_empty())
                    && templates.contains_key(TOOL_USE_CHAT_TEMPLATE_NAME)
                {
                    TOOL_USE_CHAT_TEMPLATE_NAME
                } else {
                    DEFAULT_CHAT_TEMPLATE_NAME
                };
                let template =
                    templates
                        .get(selected_name)
                        .ok_or_else(|| Error::AmbiguousChatTemplate {
                            available: templates.keys().cloned().collect(),
                        })?;
                Ok(SelectedChatTemplate {
                    template,
                    identity: ChatTemplateIdentity::Named(selected_name.to_owned()),
                })
            }
        }
    }
}

/// Wrapper around [`tokenizers::Tokenizer`] and [`minijinja::Environment`]
/// providing more utilities.
pub struct Tokenizer {
    inner: tokenizers::Tokenizer,
    env: Environment<'static>,
    template_kwargs: serde_json::Map<String, serde_json::Value>,
}

impl FromStr for Tokenizer {
    type Err = tokenizers::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        tokenizers::Tokenizer::from_str(s).map(Self::from_tokenizer)
    }
}

impl Tokenizer {
    pub fn from_tokenizer(tokenizer: tokenizers::Tokenizer) -> Self {
        let mut env = Environment::new();
        env.set_unknown_method_callback(minijinja_contrib::pycompat::unknown_method_callback);
        Self {
            inner: tokenizer,
            env,
            template_kwargs: serde_json::Map::new(),
        }
    }

    pub fn set_template_kwargs(
        &mut self,
        template_kwargs: serde_json::Map<String, serde_json::Value>,
    ) {
        self.template_kwargs = template_kwargs;
    }

    pub fn template_kwargs(&self) -> &serde_json::Map<String, serde_json::Value> {
        &self.template_kwargs
    }

    pub fn from_file(file: impl AsRef<Path>) -> tokenizers::Result<Self> {
        tokenizers::Tokenizer::from_file(file).map(Self::from_tokenizer)
    }

    pub fn from_bytes(bytes: impl AsRef<[u8]>) -> tokenizers::Result<Self> {
        tokenizers::Tokenizer::from_bytes(bytes).map(Self::from_tokenizer)
    }

    pub fn apply_chat_template<'a, I, R, T>(
        &'a mut self,
        model_template: impl Into<ModelChatTemplate>,
        args: ApplyChatTemplateArgs<'a, I, R, T>,
    ) -> Result<Vec<String>, Error>
    where
        I: IntoIterator<Item = Chat<'a, R, T>>,
        R: Serialize + 'a,
        T: Serialize + 'a,
    {
        apply_chat_template_with_default_kwargs(
            &mut self.env,
            model_template.into(),
            args,
            Some(&self.template_kwargs),
        )
    }

    pub fn apply_chat_template_and_encode<'a, I, R, T>(
        &mut self,
        model_template: impl Into<ModelChatTemplate>,
        args: ApplyChatTemplateArgs<'a, I, R, T>,
    ) -> Result<Vec<Encoding>, Error>
    where
        I: IntoIterator<Item = Chat<'a, R, T>>,
        R: Serialize + 'a,
        T: Serialize + 'a,
    {
        let Self {
            inner,
            env,
            template_kwargs,
        } = self;

        let rendered_chats = apply_chat_template_with_default_kwargs(
            env,
            model_template.into(),
            args,
            Some(template_kwargs),
        )?;
        inner
            .encode_batch(rendered_chats, false)
            .map_err(Into::into)
    }

    pub fn apply_chat_template_json<'a, I>(
        &mut self,
        model_template: impl Into<ModelChatTemplate>,
        conversations: I,
        tools: Option<&'a [serde_json::Value]>,
        model_id: &'a str,
        add_generation_prompt: bool,
        template_kwargs: Option<&'a serde_json::Map<String, serde_json::Value>>,
    ) -> Result<Vec<String>, Error>
    where
        I: IntoIterator<Item = Vec<serde_json::Value>>,
    {
        apply_chat_template_json_with_default_kwargs(
            &mut self.env,
            model_template.into(),
            conversations,
            tools,
            model_id,
            add_generation_prompt,
            Some(&self.template_kwargs),
            template_kwargs,
        )
    }
}

impl Deref for Tokenizer {
    type Target = tokenizers::Tokenizer;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl DerefMut for Tokenizer {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.inner
    }
}

#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    System,
    User,
    Assistant,
}

#[derive(Debug, Clone, Serialize)]
pub enum Content {
    String(String),
    Map(HashMap<String, String>),
}

#[derive(Debug, Clone, Serialize)]
pub struct Conversation<R, T> {
    pub role: R,
    pub content: T,
}

#[derive(Debug, Clone, Serialize)]
#[serde(untagged)]
pub enum Chat<'a, R, T> {
    Borrowed(&'a [Conversation<R, T>]),
    Owned(Vec<Conversation<R, T>>),
}

impl<R, T> Deref for Chat<'_, R, T> {
    type Target = [Conversation<R, T>];

    fn deref(&self) -> &Self::Target {
        match self {
            Chat::Borrowed(conversations) => conversations,
            Chat::Owned(conversations) => conversations,
        }
    }
}

impl<R, T> From<Vec<Conversation<R, T>>> for Chat<'_, R, T> {
    fn from(value: Vec<Conversation<R, T>>) -> Self {
        Chat::Owned(value)
    }
}

impl<'a, R, T> From<&'a [Conversation<R, T>]> for Chat<'a, R, T> {
    fn from(value: &'a [Conversation<R, T>]) -> Self {
        Chat::Borrowed(value)
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct Document {
    pub title: String,
    pub text: String,
}

pub enum Padding {
    Longest,
    MaxLength,
}

pub enum Truncation {
    MaxLength(usize),
}

#[derive(Debug, Clone, Serialize)]
#[serde(transparent)]
pub struct JsonConversation(pub Vec<serde_json::Value>);

#[derive(Default)]
pub struct ApplyChatTemplateArgs<'a, I, R = Role, T = String>
where
    I: IntoIterator<Item = Chat<'a, R, T>>,
    R: Serialize + 'a,
    T: Serialize + 'a,
{
    // pub conversations: &'a [Conversation<R, T>],
    pub conversations: I,
    pub tools: Option<&'a [serde_json::Value]>,
    pub documents: Option<&'a [Document]>,
    pub model_id: &'a str,
    pub chat_template_id: Option<&'a str>,
    pub add_generation_prompt: Option<bool>,
    pub continue_final_message: Option<bool>,
    pub template_kwargs: Option<&'a serde_json::Map<String, serde_json::Value>>,
}

pub fn load_model_chat_template_from_str(
    content: &str,
) -> std::io::Result<Option<ModelChatTemplate>> {
    let config =
        serde_json::from_str::<serde_json::Value>(content).map_err(std::io::Error::from)?;
    let Some(value) = config.get("chat_template") else {
        return Ok(None);
    };
    if value.is_null() {
        return Ok(None);
    }
    if let Some(template) = value.as_str() {
        return Ok(Some(ModelChatTemplate::Single(template.to_owned())));
    }
    let Some(entries) = value.as_array() else {
        return Err(invalid_chat_template(
            "expected a string or an array of named template entries".into(),
        ));
    };
    if entries.is_empty() {
        return Err(invalid_chat_template(
            "named template collection must not be empty".into(),
        ));
    }

    let mut templates = BTreeMap::new();
    for (index, entry) in entries.iter().enumerate() {
        let Some(entry) = entry.as_object() else {
            return Err(invalid_chat_template(format!(
                "entry {index} must be an object with string fields \"name\" and \"template\""
            )));
        };
        if entry.len() != 2 || !entry.contains_key("name") || !entry.contains_key("template") {
            return Err(invalid_chat_template(format!(
                "entry {index} must contain exactly the fields \"name\" and \"template\""
            )));
        }
        let Some(name) = entry.get("name").and_then(serde_json::Value::as_str) else {
            return Err(invalid_chat_template(format!(
                "entry {index} field \"name\" must be a string"
            )));
        };
        if name.is_empty() {
            return Err(invalid_chat_template(format!(
                "entry {index} field \"name\" must not be empty"
            )));
        }
        let Some(template) = entry.get("template").and_then(serde_json::Value::as_str) else {
            return Err(invalid_chat_template(format!(
                "entry {index} field \"template\" must be a string"
            )));
        };
        if templates
            .insert(name.to_owned(), template.to_owned())
            .is_some()
        {
            return Err(invalid_chat_template(format!(
                "duplicate named template {name:?}"
            )));
        }
    }

    Ok(Some(ModelChatTemplate::Named(templates)))
}

pub fn load_model_chat_template_from_file(
    file: impl AsRef<Path>,
) -> std::io::Result<Option<ModelChatTemplate>> {
    let content = read_to_string(file)?;
    load_model_chat_template_from_str(&content)
}

fn invalid_chat_template(message: String) -> std::io::Error {
    std::io::Error::new(
        std::io::ErrorKind::InvalidData,
        Error::InvalidChatTemplate(message),
    )
}

/// Returns undeclared top-level variables referenced by a chat template.
///
/// This is static template analysis: it identifies variables that might be
/// looked up at render time, but it does not infer value types or defaults.
pub fn chat_template_variables(
    model_template: &str,
    model_id: &str,
) -> Result<BTreeSet<String>, Error> {
    let mut env = Environment::new();
    env.set_unknown_method_callback(minijinja_contrib::pycompat::unknown_method_callback);
    env.add_template_owned(model_id.to_owned(), model_template.to_owned())?;
    let template = env.get_template(model_id)?;
    Ok(template.undeclared_variables(false).into_iter().collect())
}

/// Returns likely user-provided kwargs referenced by a chat template.
///
/// The result excludes the standard chat-template variables provided by this
/// crate and MiniJinja's registered globals. It remains best-effort because
/// Jinja templates do not carry a formal kwarg schema.
pub fn chat_template_kwargs(
    model_template: &str,
    model_id: &str,
) -> Result<BTreeSet<String>, Error> {
    let mut env = Environment::new();
    env.set_unknown_method_callback(minijinja_contrib::pycompat::unknown_method_callback);
    env.add_template_owned(model_id.to_owned(), model_template.to_owned())?;
    let template = env.get_template(model_id)?;
    let globals = env
        .globals()
        .map(|(name, _)| name.to_string())
        .collect::<BTreeSet<_>>();

    Ok(template
        .undeclared_variables(false)
        .into_iter()
        .filter(|name| !STANDARD_CHAT_TEMPLATE_VARIABLES.contains(&name.as_str()))
        .filter(|name| !globals.contains(name))
        .collect())
}

const STANDARD_CHAT_TEMPLATE_VARIABLES: &[&str] = &[
    "messages",
    "tools",
    "documents",
    "add_generation_prompt",
    "raise_exception",
    "strftime_now",
];

// chat_template = self.get_chat_template(chat_template, tools)

// if isinstance(conversation, (list, tuple)) and (
//     isinstance(conversation[0], (list, tuple)) or hasattr(conversation[0], "messages")
// ):
//     conversations = conversation
//     is_batched = True
// else:
//     conversations = [conversation]
//     is_batched = False

// if continue_final_message:
//     if add_generation_prompt:
//         raise ValueError(
//             "continue_final_message and add_generation_prompt are not compatible. Use continue_final_message when you want the model to continue the final message, and add_generation_prompt when you want to add a header that will prompt it to start a new assistant message instead."
//         )
//     if return_assistant_tokens_mask:
//         raise ValueError("continue_final_message is not compatible with return_assistant_tokens_mask.")

// template_kwargs = {**self.special_tokens_map, **kwargs}  # kwargs overwrite special tokens if both are present
// rendered_chat, generation_indices = render_jinja_template(
//     conversations=conversations,
//     tools=tools,
//     documents=documents,
//     chat_template=chat_template,
//     return_assistant_tokens_mask=return_assistant_tokens_mask,
//     continue_final_message=continue_final_message,
//     add_generation_prompt=add_generation_prompt,
//     **template_kwargs,
// )

// if not is_batched:
//     rendered_chat = rendered_chat[0]

// if tokenize:
//     out = self(
//         rendered_chat,
//         padding=padding,
//         truncation=truncation,
//         max_length=max_length,
//         add_special_tokens=False,
//         return_tensors=return_tensors,
//         **tokenizer_kwargs,
//     )
//     if return_dict:
//         if return_assistant_tokens_mask:
//             assistant_masks = []
//             if is_batched or return_tensors:
//                 input_ids = out["input_ids"]
//             else:
//                 input_ids = [out["input_ids"]]
//             for i in range(len(input_ids)):
//                 current_mask = [0] * len(input_ids[i])
//                 for assistant_start_char, assistant_end_char in generation_indices[i]:
//                     start_token = out.char_to_token(i, assistant_start_char)
//                     end_token = out.char_to_token(i, assistant_end_char - 1)
//                     if start_token is None:
//                         # start_token is out of bounds maybe due to truncation.
//                         break
//                     for token_id in range(start_token, end_token + 1 if end_token else len(input_ids[i])):
//                         current_mask[token_id] = 1
//                 assistant_masks.append(current_mask)

//             if not is_batched and not return_tensors:
//                 assistant_masks = assistant_masks[0]

//             out["assistant_masks"] = assistant_masks

//             if return_tensors:
//                 out.convert_to_tensors(tensor_type=return_tensors)

//         return out
//     else:
//         return out["input_ids"]
// else:
//     return rendered_chat

// def render_jinja_template(
//     conversations: list[list[dict[str, str]]],
//     tools: Optional[list[Union[dict, Callable]]] = None,
//     documents: Optional[list[dict[str, str]]] = None,
//     chat_template: Optional[str] = None,
//     return_assistant_tokens_mask: Optional[bool] = False,
//     continue_final_message: Optional[bool] = False,
//     add_generation_prompt: Optional[bool] = False,
//     **kwargs,
// ) -> str:
//     if return_assistant_tokens_mask and not re.search(r"\{\%-?\s*generation\s*-?\%\}", chat_template):
//         logger.warning_once(
//             "return_assistant_tokens_mask==True but chat template does not contain `{% generation %}` keyword."
//         )

//     # Compilation function uses a cache to avoid recompiling the same template
//     compiled_template = _compile_jinja_template(chat_template)

//     # We accept either JSON schemas or functions for tools. If we get functions, we convert them to schemas
//     if tools is not None:
//         tool_schemas = []
//         for tool in tools:
//             if isinstance(tool, dict):
//                 tool_schemas.append(tool)
//             elif isfunction(tool):
//                 tool_schemas.append(get_json_schema(tool))
//             else:
//                 raise ValueError(
//                     "Tools should either be a JSON schema, or a callable function with type hints "
//                     "and a docstring suitable for auto-conversion to a schema."
//                 )
//     else:
//         tool_schemas = None

//     if documents is not None:
//         for document in documents:
//             if not isinstance(document, dict):
//                 raise TypeError("Documents should be a list of dicts with 'title' and 'text' keys!")

//     rendered = []
//     all_generation_indices = []
//     for chat in conversations:
//         if hasattr(chat, "messages"):
//             # Indicates it's a Conversation object
//             chat = chat.messages
//         if return_assistant_tokens_mask:
//             rendered_chat, generation_indices = _render_with_assistant_indices(
//                 compiled_template=compiled_template,
//                 messages=chat,
//                 tools=tool_schemas,
//                 documents=documents,
//                 add_generation_prompt=add_generation_prompt,
//                 **kwargs,
//             )
//             all_generation_indices.append(generation_indices)
//         else:
//             rendered_chat = compiled_template.render(
//                 messages=chat,
//                 tools=tool_schemas,
//                 documents=documents,
//                 add_generation_prompt=add_generation_prompt,
//                 **kwargs,
//             )
//         if continue_final_message:
//             final_message = chat[-1]["content"]
//             if isinstance(final_message, (list, tuple)):
//                 for content_block in reversed(final_message):
//                     if "text" in content_block:
//                         # Pick the last text block in the message (the first one we hit while iterating in reverse)
//                         final_message = content_block["text"]
//                         break
//                 else:
//                     raise ValueError(
//                         "continue_final_message is set but we could not find any text to continuein the final message!"
//                     )
//             if final_message.strip() not in rendered_chat:
//                 raise ValueError(
//                     "continue_final_message is set but the final message does not appear in the chat after "
//                     "applying the chat template! This can happen if the chat template deletes portions of "
//                     "the final message. Please verify the chat template and final message in your chat to "
//                     "ensure they are compatible."
//                 )
//             final_msg_loc = rendered_chat.rindex(final_message.strip())
//             if rendered_chat[final_msg_loc : final_msg_loc + len(final_message.lstrip())] == final_message:
//                 # The template preserves spacing or the message doesn't have trailing spacing, so things are simple
//                 rendered_chat = rendered_chat[: final_msg_loc + len(final_message.lstrip())]
//             else:
//                 # The message has trailing spacing that was trimmed, so we must be more cautious
//                 rendered_chat = rendered_chat[: final_msg_loc + len(final_message.strip())]
//         rendered.append(rendered_chat)

//     return rendered, all_generation_indices

pub fn apply_chat_template_json<'a, I>(
    env: &mut Environment<'static>,
    model_template: impl Into<ModelChatTemplate>,
    conversations: I,
    tools: Option<&'a [serde_json::Value]>,
    model_id: &'a str,
    add_generation_prompt: bool,
    template_kwargs: Option<&'a serde_json::Map<String, serde_json::Value>>,
) -> Result<Vec<String>, Error>
where
    I: IntoIterator<Item = Vec<serde_json::Value>>,
{
    apply_chat_template_json_with_default_kwargs(
        env,
        model_template.into(),
        conversations,
        tools,
        model_id,
        add_generation_prompt,
        None,
        template_kwargs,
    )
}

fn apply_chat_template_json_with_default_kwargs<'a, I>(
    env: &mut Environment<'static>,
    model_template: ModelChatTemplate,
    conversations: I,
    tools: Option<&'a [serde_json::Value]>,
    model_id: &'a str,
    add_generation_prompt: bool,
    default_template_kwargs: Option<&serde_json::Map<String, serde_json::Value>>,
    template_kwargs: Option<&'a serde_json::Map<String, serde_json::Value>>,
) -> Result<Vec<String>, Error>
where
    I: IntoIterator<Item = Vec<serde_json::Value>>,
{
    let conversations = conversations.into_iter().map(|conversation| {
        Chat::Owned(vec![Conversation {
            role: serde_json::Value::Null,
            content: JsonConversation(conversation),
        }])
    });

    apply_chat_template_with_default_kwargs(
        env,
        model_template,
        ApplyChatTemplateArgs {
            conversations,
            tools,
            documents: None,
            model_id,
            chat_template_id: None,
            add_generation_prompt: Some(add_generation_prompt),
            continue_final_message: None,
            template_kwargs,
        },
        default_template_kwargs,
    )
}

pub fn apply_chat_template<'a, I, R, T>(
    env: &mut Environment<'static>,
    model_template: impl Into<ModelChatTemplate>,
    args: ApplyChatTemplateArgs<'a, I, R, T>,
) -> Result<Vec<String>, Error>
where
    I: IntoIterator<Item = Chat<'a, R, T>>,
    R: Serialize + 'a,
    T: Serialize + 'a,
{
    apply_chat_template_with_default_kwargs(env, model_template.into(), args, None)
}

fn apply_chat_template_with_default_kwargs<'a, I, R, T>(
    env: &mut Environment<'static>,
    model_template: ModelChatTemplate,
    args: ApplyChatTemplateArgs<'a, I, R, T>,
    default_template_kwargs: Option<&serde_json::Map<String, serde_json::Value>>,
) -> Result<Vec<String>, Error>
where
    I: IntoIterator<Item = Chat<'a, R, T>>,
    R: Serialize + 'a,
    T: Serialize + 'a,
{
    let ApplyChatTemplateArgs {
        conversations,
        tools,
        documents,
        model_id,
        chat_template_id,
        add_generation_prompt,
        continue_final_message,
        template_kwargs,
    } = args;

    let add_generation_prompt = add_generation_prompt.unwrap_or(false);
    let continue_final_message = continue_final_message.unwrap_or(false);
    let selected = model_template.select(tools)?;

    let template = match chat_template_id {
        Some(chat_template_id) => env.get_template(chat_template_id)?,
        None => {
            let selected_template_id = match selected.identity() {
                ChatTemplateIdentity::Single => model_id.to_owned(),
                ChatTemplateIdentity::Named(name) => {
                    format!("{model_id}::chat_template::{name}")
                }
            };
            match env.get_template(&selected_template_id) {
                Ok(template) => template,
                Err(_) => {
                    env.add_template_owned(
                        selected_template_id.clone(),
                        selected.template().to_owned(),
                    )?;
                    env.get_template(&selected_template_id)
                        .expect("Newly added template must be present")
                }
            }
        }
    };

    // TODO: allow return_generation_indices

    render_jinja_tempalte(
        template,
        conversations,
        tools,
        documents,
        Some(add_generation_prompt),
        Some(continue_final_message),
        default_template_kwargs,
        template_kwargs,
    )
}

// TODO: render with assistant indices
fn render_jinja_tempalte<'a, R, T>(
    template: Template,
    conversations: impl IntoIterator<Item = Chat<'a, R, T>>,
    tools: Option<&'a [serde_json::Value]>,
    documents: Option<&'a [Document]>,
    add_generation_prompt: Option<bool>,
    continue_final_message: Option<bool>,
    default_template_kwargs: Option<&serde_json::Map<String, serde_json::Value>>,
    template_kwargs: Option<&'a serde_json::Map<String, serde_json::Value>>,
) -> Result<Vec<String>, Error>
where
    R: Serialize + 'a,
    T: Serialize + 'a,
{
    let add_generation_prompt = add_generation_prompt.unwrap_or(false);
    let continue_final_message = continue_final_message.unwrap_or(false);

    // TODO: what does checking for "messages" key do in the python code?
    let mut rendered = Vec::new();
    for chat in conversations {
        let empty_tools: &[serde_json::Value] = &[];
        let empty_documents: &[Document] = &[];
        let tools = tools.unwrap_or(empty_tools);
        let documents = documents.unwrap_or(empty_documents);
        let messages = if chat.len() == 1 {
            serde_json::to_value(&chat[0].content)
                .ok()
                .and_then(|value| match value {
                    serde_json::Value::Array(messages)
                        if serde_json::to_value(&chat[0].role).ok()
                            == Some(serde_json::Value::Null) =>
                    {
                        Some(serde_json::Value::Array(messages))
                    }
                    _ => None,
                })
        } else {
            None
        }
        .unwrap_or_else(|| serde_json::to_value(&chat).unwrap_or(serde_json::Value::Null));

        let mut context = serde_json::Map::new();
        context.insert("messages".to_string(), messages);
        context.insert("tools".to_string(), serde_json::to_value(tools)?);
        context.insert("documents".to_string(), serde_json::to_value(documents)?);
        context.insert(
            "add_generation_prompt".to_string(),
            serde_json::Value::Bool(add_generation_prompt),
        );
        if let Some(default_template_kwargs) = default_template_kwargs {
            context.extend(default_template_kwargs.clone());
        }
        if let Some(template_kwargs) = template_kwargs {
            context.extend(template_kwargs.clone());
        }

        let mut rendered_chat = template.render(context)?;
        rendered_chat = rendered_chat.trim_start_matches('\n').to_string();

        if continue_final_message {
            let Some(final_message) = chat
                .last()
                .and_then(|chat| serde_json::to_value(&chat.content).ok())
                .and_then(|value| match value {
                    serde_json::Value::String(text) => Some(text),
                    other => other
                        .get("text")
                        .or_else(|| other.get("content"))
                        .and_then(|value| value.as_str())
                        .map(ToString::to_string),
                })
            else {
                continue;
            };

            let final_message_str = final_message;

            if !rendered_chat.contains(final_message_str.trim()) {
                return Err(Error::FinalMsgNotInChat);
            }

            let final_msg_loc = rendered_chat.rfind(&final_message_str.trim()).unwrap();
            let final_msg_len = final_message_str.trim_start().len();
            rendered_chat = if rendered_chat[final_msg_loc..final_msg_loc + final_msg_len]
                == final_message_str
            {
                // The template preserves spacing or the message doesn't have trailing spacing, so things are simple
                rendered_chat[..final_msg_loc + final_msg_len].to_string()
            } else {
                // The message has trailing spacing that was trimmed, so we must be more cautious
                rendered_chat[..final_msg_loc + final_message_str.trim().len()].to_string()
            };
        }
        rendered.push(rendered_chat);
    }

    Ok(rendered)
}

#[cfg(test)]
mod tests {
    use minijinja::Environment;
    use std::path::PathBuf;

    use crate::tokenizer::{
        apply_chat_template, apply_chat_template_json, load_model_chat_template_from_file,
        load_model_chat_template_from_str, ApplyChatTemplateArgs, ChatTemplateIdentity,
        Conversation, Role,
    };

    /// Returns the path to test fixtures. Uses TEST_MODEL_DIR env var if set,
    /// otherwise falls back to the fixtures bundled in the repo.
    fn fixtures_dir() -> PathBuf {
        std::env::var("TEST_MODEL_DIR")
            .map(PathBuf::from)
            .unwrap_or_else(|_| {
                PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/qwen3")
            })
    }

    #[test]
    fn test_load_chat_template_from_file() {
        let file = fixtures_dir().join("tokenizer_config.json");
        let chat_template = load_model_chat_template_from_file(file).unwrap().unwrap();
        assert!(!chat_template.select(None).unwrap().template().is_empty());
    }

    #[test]
    fn single_chat_template_remains_compatible() {
        let templates = load_model_chat_template_from_str(r#"{"chat_template":"single-template"}"#)
            .unwrap()
            .unwrap();
        let selected = templates.select(None).unwrap();
        assert_eq!(selected.template(), "single-template");
        assert_eq!(selected.identity(), &ChatTemplateIdentity::Single);

        let selected_with_tools = templates.select(Some(&[serde_json::json!({})])).unwrap();
        assert_eq!(selected_with_tools.template(), "single-template");
        assert_eq!(
            selected_with_tools.identity(),
            &ChatTemplateIdentity::Single
        );
    }

    #[test]
    fn named_chat_templates_select_default_or_tool_use() {
        let templates = load_model_chat_template_from_str(
            r#"{
                "chat_template": [
                    {"name": "tool_use", "template": "tools-template"},
                    {"name": "default", "template": "default-template"}
                ]
            }"#,
        )
        .unwrap()
        .unwrap();

        let selected = templates.select(None).unwrap();
        assert_eq!(selected.template(), "default-template");
        assert_eq!(
            selected.identity(),
            &ChatTemplateIdentity::Named("default".into())
        );

        let selected = templates.select(Some(&[])).unwrap();
        assert_eq!(selected.template(), "default-template");
        assert_eq!(
            selected.identity(),
            &ChatTemplateIdentity::Named("default".into())
        );

        let tools = [serde_json::json!({"type": "function"})];
        let selected = templates.select(Some(&tools)).unwrap();
        assert_eq!(selected.template(), "tools-template");
        assert_eq!(
            selected.identity(),
            &ChatTemplateIdentity::Named("tool_use".into())
        );

        let default_only = load_model_chat_template_from_str(
            r#"{"chat_template":[{"name":"default","template":"default-only"}]}"#,
        )
        .unwrap()
        .unwrap();
        let selected = default_only.select(Some(&tools)).unwrap();
        assert_eq!(selected.template(), "default-only");
        assert_eq!(
            selected.identity(),
            &ChatTemplateIdentity::Named("default".into())
        );
    }

    #[test]
    fn named_chat_template_selection_reports_missing_default_deterministically() {
        let templates = load_model_chat_template_from_str(
            r#"{"chat_template":[
                {"name":"rag","template":"rag-template"},
                {"name":"chat","template":"chat-template"}
            ]}"#,
        )
        .unwrap()
        .unwrap();

        assert_eq!(
            templates.select(None).unwrap_err().to_string(),
            r#"chat_template collection has no default template; available templates: ["chat", "rag"]"#
        );
    }

    #[test]
    fn named_chat_template_collection_rejects_malformed_and_duplicate_entries() {
        let cases = [
            (
                r#"{"chat_template":{}}"#,
                "invalid chat_template: expected a string or an array of named template entries",
            ),
            (
                r#"{"chat_template":[]}"#,
                "invalid chat_template: named template collection must not be empty",
            ),
            (
                r#"{"chat_template":["default"]}"#,
                "invalid chat_template: entry 0 must be an object with string fields \"name\" and \"template\"",
            ),
            (
                r#"{"chat_template":[{"template":"x"}]}"#,
                "invalid chat_template: entry 0 must contain exactly the fields \"name\" and \"template\"",
            ),
            (
                r#"{"chat_template":[{"name":"default","template":1}]}"#,
                "invalid chat_template: entry 0 field \"template\" must be a string",
            ),
            (
                r#"{"chat_template":[{"name":"default","template":"a"},{"name":"default","template":"b"}]}"#,
                "invalid chat_template: duplicate named template \"default\"",
            ),
        ];

        for (config, expected) in cases {
            assert_eq!(
                load_model_chat_template_from_str(config)
                    .unwrap_err()
                    .to_string(),
                expected
            );
        }
    }

    #[test]
    fn apply_chat_template_apis_share_named_template_selection() {
        let templates = load_model_chat_template_from_str(
            r#"{
                "chat_template": [
                    {"name": "default", "template": "default"},
                    {"name": "tool_use", "template": "tool_use"}
                ]
            }"#,
        )
        .unwrap()
        .unwrap();
        let mut env = Environment::new();
        let conversations = [vec![Conversation {
            role: Role::User,
            content: "hello",
        }]
        .into()];

        let rendered = apply_chat_template(
            &mut env,
            templates.clone(),
            ApplyChatTemplateArgs {
                conversations,
                tools: Some(&[]),
                documents: None,
                model_id: "selection-test",
                chat_template_id: None,
                add_generation_prompt: None,
                continue_final_message: None,
                template_kwargs: None,
            },
        )
        .unwrap();
        assert_eq!(rendered, vec!["default"]);

        let tools = [serde_json::json!({"type": "function"})];
        let rendered = apply_chat_template_json(
            &mut env,
            templates,
            [vec![
                serde_json::json!({"role": "user", "content": "hello"}),
            ]],
            Some(&tools),
            "selection-test",
            false,
            None,
        )
        .unwrap();
        assert_eq!(rendered, vec!["tool_use"]);
    }

    #[test]
    fn test_apply_chat_template() {
        let file = fixtures_dir().join("tokenizer_config.json");
        let model_chat_template = load_model_chat_template_from_file(file).unwrap().unwrap();
        assert!(!model_chat_template
            .select(None)
            .unwrap()
            .template()
            .is_empty());

        let model_id = "mlx-community/Qwen3-4B-bf16".to_string();
        let conversations = vec![Conversation {
            role: Role::User,
            content: "hello",
        }];
        let args = ApplyChatTemplateArgs {
            conversations: [conversations.into()],
            tools: None,
            documents: None,
            model_id: &model_id,
            chat_template_id: None,
            add_generation_prompt: None,
            continue_final_message: None,
            template_kwargs: None,
        };

        let mut env = Environment::new();
        env.set_unknown_method_callback(minijinja_contrib::pycompat::unknown_method_callback);

        let rendered_chat = apply_chat_template(&mut env, model_chat_template, args).unwrap();
        println!("{:?}", rendered_chat);
    }

    #[test]
    fn test_apply_chat_template_with_template_kwargs() {
        let model_template =
            "{% if enable_thinking %}think{% else %}no-think{% endif %}".to_string();
        let model_id = "test-model".to_string();
        let conversations = vec![Conversation {
            role: Role::User,
            content: "hello",
        }];
        let mut template_kwargs = serde_json::Map::new();
        template_kwargs.insert(
            "enable_thinking".to_string(),
            serde_json::Value::Bool(false),
        );
        let args = ApplyChatTemplateArgs {
            conversations: [conversations.into()],
            tools: None,
            documents: None,
            model_id: &model_id,
            chat_template_id: None,
            add_generation_prompt: None,
            continue_final_message: None,
            template_kwargs: Some(&template_kwargs),
        };

        let mut env = Environment::new();
        env.set_unknown_method_callback(minijinja_contrib::pycompat::unknown_method_callback);

        let rendered_chat = apply_chat_template(&mut env, model_template, args).unwrap();
        assert_eq!(rendered_chat, vec!["no-think"]);
    }

    #[test]
    fn test_tokenizer_template_kwargs_defaults_can_be_overridden() {
        let raw = tokenizers::Tokenizer::new(tokenizers::models::wordlevel::WordLevel::default());
        let mut tokenizer = super::Tokenizer::from_tokenizer(raw);
        tokenizer.set_template_kwargs(serde_json::Map::from_iter([
            (
                "bos_token".to_string(),
                serde_json::Value::String("<bos>".to_string()),
            ),
            (
                "tone".to_string(),
                serde_json::Value::String("default".to_string()),
            ),
        ]));
        let model_template =
            "{{ bos_token }}{{ messages[0].role }}: {{ messages[0].content }} {{ tone }}"
                .to_string();
        let model_id = "test-model".to_string();
        let conversations = vec![Conversation {
            role: Role::User,
            content: "hello",
        }];
        let mut template_kwargs = serde_json::Map::new();
        template_kwargs.insert(
            "tone".to_string(),
            serde_json::Value::String("override".to_string()),
        );

        let rendered_chat = tokenizer
            .apply_chat_template(
                model_template,
                ApplyChatTemplateArgs {
                    conversations: [conversations.into()],
                    tools: None,
                    documents: None,
                    model_id: &model_id,
                    chat_template_id: None,
                    add_generation_prompt: None,
                    continue_final_message: None,
                    template_kwargs: Some(&template_kwargs),
                },
            )
            .unwrap();

        assert_eq!(rendered_chat, vec!["<bos>user: hello override"]);
    }

    #[test]
    fn test_chat_template_kwargs_filters_standard_variables_and_globals() {
        let model_template = concat!(
            "{% set ns = namespace(found=false) %}",
            "{% for message in messages %}{{ message.role }}{% endfor %}",
            "{% if tools %}{{ tools|length }}{% endif %}",
            "{% if documents %}{{ documents|length }}{% endif %}",
            "{% if add_generation_prompt and enable_thinking is defined %}{{ tone }}{% endif %}",
        );

        let kwargs = super::chat_template_kwargs(model_template, "test-model").unwrap();
        assert_eq!(
            kwargs.into_iter().collect::<Vec<_>>(),
            vec!["enable_thinking", "tone"]
        );
    }

    #[test]
    fn test_qwen_fixture_reports_enable_thinking_kwarg() {
        let file = fixtures_dir().join("tokenizer_config.json");
        let chat_template = load_model_chat_template_from_file(file).unwrap().unwrap();
        let kwargs = super::chat_template_kwargs(
            chat_template.select(None).unwrap().template(),
            "qwen-fixture",
        )
        .unwrap();
        assert!(kwargs.contains("enable_thinking"), "{kwargs:?}");
    }

    #[test]
    #[ignore = "requires local model files (tokenizer.json is 11MB)"]
    fn test_tokenizer_apply_chat_template() {
        let tokenizer_file = fixtures_dir().join("tokenizer.json");
        let tokenizer_config_file = fixtures_dir().join("tokenizer_config.json");

        let model_id = "mlx-community/Qwen3-4B-bf16".to_string();

        let conversations = vec![Conversation {
            role: Role::User,
            content: "hello",
        }];

        let mut tokenizer = super::Tokenizer::from_file(tokenizer_file).unwrap();

        let model_chat_template = load_model_chat_template_from_file(tokenizer_config_file)
            .unwrap()
            .unwrap();
        assert!(!model_chat_template
            .select(None)
            .unwrap()
            .template()
            .is_empty());

        let args = ApplyChatTemplateArgs {
            conversations: [conversations.into()],
            tools: None,
            documents: None,
            model_id: &model_id,
            chat_template_id: None,
            add_generation_prompt: None,
            continue_final_message: None,
            template_kwargs: None,
        };

        let rendered_chat = tokenizer
            .apply_chat_template(model_chat_template, args)
            .unwrap();
        println!("{:?}", rendered_chat);
    }

    #[test]
    #[ignore = "requires local model files (tokenizer.json is 11MB)"]
    fn test_tokenizer_apply_chat_template_and_encode() {
        let tokenizer_file = fixtures_dir().join("tokenizer.json");
        let tokenizer_config_file = fixtures_dir().join("tokenizer_config.json");

        let model_id = "mlx-community/Qwen3-4B-bf16".to_string();

        let conversations = vec![Conversation {
            role: Role::User,
            content: "hello",
        }];
        let mut tokenizer = super::Tokenizer::from_file(tokenizer_file).unwrap();

        let model_chat_template = load_model_chat_template_from_file(tokenizer_config_file)
            .unwrap()
            .unwrap();
        assert!(!model_chat_template
            .select(None)
            .unwrap()
            .template()
            .is_empty());

        let args = ApplyChatTemplateArgs {
            conversations: [conversations.into()],
            tools: None,
            documents: None,
            model_id: &model_id,
            chat_template_id: None,
            add_generation_prompt: None,
            continue_final_message: None,
            template_kwargs: None,
        };

        let encodings = tokenizer
            .apply_chat_template_and_encode(model_chat_template, args)
            .unwrap();
        println!("{:?}", encodings.iter().flat_map(|e| e.get_ids()));
    }
}
